---
title: 'Math 4317 (Prof. Swiech, S''18): HW #1'
author: "Peter Williams"
date: "1/25/2018"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Section 1
*F. Show that the symmetric difference $D$, defined in the preceding exercise is also given by $D = (A \cup B) \setminus (A \cap B)$*
Show $D = (A \setminus B ) \cup (B \setminus A) = (A \cup B ) \setminus (A \cap B)$: 

First, $x \in (A \setminus B ) \cup (B \setminus A) \implies x \in (A \setminus B)$ or $x \in (B \setminus A) \implies$, $x$ is in $A$ but not $B$, or, $x$ is in $B$ but not $A \implies x$ is in $A$ or $B$ but not in $A$ and $B \implies x \in (A \cup B) \setminus (A \cap B)$.

In the other direction, $x \in (A \cup B) \setminus (A \cap B) \implies x \in (A \cup B)$ but not in $(A \cap B) \implies x$ is in $A$ but not $B$, or, $x$ is in $B$ but not $A \implies x \in (A \setminus B)$ or $x \in (B \setminus A) \implies x \in (A \setminus B) \cup (B \setminus A) \implies (A \setminus B ) \cup (B \setminus A) = (A \cup B ) \setminus (A \cap B)$\newline

*I. If $\{A_1,A_2, ...,A_n \}$ is a collection of sets, and if E is any set, show that:*
$$(i)\ \ E \cap \cup_{j=1}^{n}A_j = \cup_{j=1}^{n} (E \cap A_j),\ and\ (ii),\ \ E \cup \cup_{j=1}^{n}A_j = \cup_{j=1}^{n} (E \cup A_j)$$
  
(i) $x \in E \cap \cup_{j=1}^{n}A_j \implies x \in E\ and\ x \in \{A_1\ or\ A2\ ... or\ A_n\} \implies x \in E$ and that there exists for some $j=1,2,...,n$ an $A_j$ such that $x \in A_j\ and\ x \in E \implies (x\in E\ and\ A_1)\ or\ (x \in E\ and\ A_2)\ ...\ or\ (x \in E\ and\ A_n) \implies x \in \cup_{j=1}^{n}(E \cap A_j)$.  
In the other direction, $x \in \cup_{j=1}^{n}(E \cap A_j) \Leftrightarrow x \in (E \cap A_1) \cup (E \cap A_2)\ ... \ \cup (E \cap A_n) \implies x \in E$ and $A_1$ or $E$ and $A_2$ ... $\implies$ there exists a $j = 1,...,n$ such that $x \in (E \cap A_j) \implies x \in E$ and $x \in A_1$ or $A_2$, ..., or $A_n \implies x \in E$ and $\cup_{j=1}^{n} A_j \implies x \in  E \cap \cup_{j=1}^{n}A_j$.  

(ii) $x \in E \cup \cup_{j=1}^{n} A_j \implies x \in E$ or $x \in A_1$ or $A_2$ ... or $A_n \implies$ for some $j=1,..,n$ that $x \in E \cup A_j \implies x \in E \cup A_1$ or $x \in E \cup A_2$ ... or $x \in E \cup A_n \implies x \in \cup_{j=1}^{n} (E \cup A_j)$. 
In the other direction, $x \in \cup_{j=1}^{n} (E \cup A_j) \Leftrightarrow x \in E \cup A_1$ or $x \in E \cup A_2$ ... or $x \in E \cup A_n \implies$ there exists some $j = 1,...,n$ such that $x \in E \cup A_j \implies (x \in E\ or\ x \in A_1)$ or $(x \in E\ or\ x \in A_2)$ ... or $(x \in E\ or\ x \in A_n) \implies x \in E$ or $x \in \cup_{j=1}^{n} A_j \implies x \in E \cup \cup_{j=1}^{n} A_j$.


*J. If $\{A_1,A_2, ...,A_n \}$ is a collection of sets, and if E is any set, show that:*
$$(i)\ E \cap \cap_{j=1}^{n}A_j = \cap_{j=1}^{n} (E \cap A_j),\ and\ (ii), \ \ E \cup \cap_{j=1}^{n}A_j = \cap_{j=1}^{n} (E \cup A_j)$$  

(i) $x \in \cap \cap_{j=1}^{n}A_j \implies x \in E$ and $x \in \cap_{j=1}^{n} A_j \implies x \in E\ and\ x \in A_j$ for all $j = 1,..,n  \implies x \in E$ and $[x \in A_1\ and\ x \in A_2\ ...\ and\ x \in A_n] \implies [x \in E\ and\ A_1]$ and ... and $[x \in E\ and\ A_n] \implies x \in \cap_{j=1}^{n} (E \cap A_j)$.
In the other direction, $x \in \cap_{j=1}^{n} (E \cap A_j) \implies x \in (E \cap A_1)$ and $a \in (E \cap A_2)$ ... and $x \in (E \cap A_n) \implies x \in (E \cap A_j)$ for all $j = 1,...,n \implies x \in E$ and $x \in A_1$ and $x \in A_2$ ... and $x \in A_n \implies x \in E$ and $x \in \cap_{j=1}^{n A_j} \implies x \in E \cap \cap_{j=1}^{n A_j}$.

(ii) $x \in E \cup \cap_{j=1}^{n}A_j \implies x \in E$ or $x \in \cap_{j=1}^{n} A_j \implies x \in E$ or $[x \in A_1$ and $x \in A_2$ ... and $x \in A_n] \implies x \in E\ or\ A_1\ and\ x \in E\ or\ A_2\ ...\ and\ x \in E\ or\ A_n \implies x \in \cap_{j=1}^{n}(E \cup A_j)$.
In the other direction, $x \in \cap_{j=1}^{n}(E \cup A_j) \implies x \in (E\ or\ A_1)\ and\ x \in (E\ or\ A_2)\ ... and\ x \in (E\ or\ A_n) \implies$ that for all $j = 1,...,n\ , x \in (E\ or\ A_j) \implies x \in E\ or\ (x \in A_1\ and\ x \in A_2 ...\ and\ x \in A_n) \implies x \in \cap_{j=1}^{n}A_j\ or\ x \in E \implies x \in E \cup \cap_{j=1}^{n}A_j$. 

\newpage

*K. Let E be a set and $\{A_1,A_2, ...,A_n \}$ be a collection of sets. Establish the De Morgan laws:*
$$(i)\ E \setminus \cap_{j=1}^{n}A_j = \cup_{j=1}^{n} (E \setminus A_j),\ and,\ (ii) \ \ E \setminus \cup_{j=1}^{n}A_j = \cap_{j=1}^{n} (E \setminus A_j)$$ 

(i) $x \in E \setminus \cap_{j=1}^{n}A_j \implies x \in E$ but not $(A_1$ and $A_2$ ... and $A_n) \implies$ there exists a $j = 1,...,n$ such that $x \in E$ but not $A_j \implies x \in E$ but not $A_1$, or $x \in E$ but not $A_2$,...,or $x \in E$ but not $A_n \implies x \in E \setminus A_1$ or $x \in E \setminus A_2$ ... or $x \in E \setminus A_n \implies x \in \cup_{j=1}^{n}(E \setminus A_j)$. In the other direction, $x \in \cup_{j=1}^{n}(E \setminus A_j) \implies x \in (E\ but\ not\ A_1)$ or $(E\ but\ not\ A_2)$ or $(E\ but\ not\ A_n) \implies$ there exists $j = 1,...,n,\ x \in E$ but not $A_j \implies x \in E$ but not $(A_1\ and\ A_2\ ...\ and\ A_n) \implies x \in E \setminus \cap_{j=1}^{n} A_j$.   

(ii) $x \in E \setminus \cup_{j=1}^{n} \implies x \in E$ but $A_1$ or $A_2$ ... or $A_n \implies x \in E$ and $x \notin A_j$ for all $j = 1,...,n \implies x \in E$ but not $A_1$, and $x \in E$ but not $A_2$, ..., and $x \in E$ but not $A_n \implies x \in (E \setminus A_1)\ and\ x \in (E \setminus A_2)\ ...\ and\ x \in (E \setminus A_n) \implies x \in \cap_{j=1}^{n}(E \setminus A_j)$. In the other direction, $x \in \cap_{j=1}^{n}(E \setminus A_j) \implies x \in (E \setminus A_1\ and\ E \setminus A_2\ ...\ and\ E \setminus A_n) \implies x \in E$ but not $A_j$ for all $j = 1,...,n \implies x \in E$ but $A_1$ or $A_2$ ... or $A_n \implies x \in E$ but not $\cup_{j=1}^{n}A_j \implies x \in E \setminus \cup_{j=1}^{n}A_j$

#### Section 2
*C. Consider the subset of $\mathbb{R}\times \mathbb{R}$ defined by $D = \{(x,y)\ :|x| + |y| = 1  \}$. Describe this set in words. Is it a function?*

This set consists of points on the line segments connecting a rotated square in the $(x,y)$ plane with vertices $(1,0)$, $(0,1)$, $(-1,0)$, and $(0,-1)$. If we attempt to define a function, with the elements $(x,y)$ from the set $D$, i.e. $y = f(x), f: x \rightarrow y$, we have $|x| + |y| = 1 \implies \sqrt{y^2} = 1 - |x| \implies y = \pm \sqrt{(1 - |x|)^2}$. $f(x) = y = \pm \sqrt{(1 - |x|)^2}$ does not fit the defintion of a function, since, as an example, the set $D$ includes the elements $(0,1)$ and $(0,-1)$, which if, $f$ is a function, $f: x \rightarrow y \implies -1 = 1$, which is clearly not true.  

*E. Prove that if $f$ is an injection from $A$ to $B$, then $f^{-1} = \{(b,a): (a,b) \in f \}$ is a function. Then prove it is an injection.*  

If $f$ is an injection, and $(a,b) \in f$, and $({a',b}) \in f$, then $a = a'$. $f^{-1} = \{(b,a) : (a,b) \in f\}$ contains the pair $(b,a)$ and $(b,a')$, and we know that $a = a'$ from the definition of $f$, so we can assume that $f^{-1}$ is a function. 
Since $f$ is injective, each unique element $b = f(a)$, is mapped to by a unique element $a$, and by definition $f^{-1} = \{(b,a) : (a,b) \in f\}$ maps the unique element $b$ back to $a$, meaning $f^{-1}(b) = a$ and $f^{-1}(b') = a$ if and only if $b = b'$, thus $f^{-1}$ is also injective. 

*H. Let $f,g$ be functions such that*
$$ g \circ f(x) = x, \ \ for\ all\ x\ in\ D(f) $$
$$ f \circ g(y) = y, \ \ for\ all\ y\ in\ D(g) $$
*Prove that $g = f^{-1}$*  

For two elements $x, x' \in D(f)$, if $f(x) = f(x') \implies g \circ f (x) = g(f(x)) = g(f(x')) \implies g(f(x)) = x = g(f(x')) = x'$, that is $x = x' \implies g \circ f$ is an injection. For two elements $y, y' \in D(g)$, if $g(y) = g(y') \implies f \circ g (y) = f(g(y)) = f(g(y')) \implies f(g(y)) = y = f(g(y')) = y'$, that is $y = y' \implies f \circ g$ is an injection, and implies $f$ and $g$ are injections as well. 

This implies $g$ can be defined $g = \{(f(x), x): (x, f(x)) \in f  \}$, which is the definition for $f^{-1}$, implying $g = f^{-1}$. 

*J. Let $f$ be the function on $\mathbb{R}$ to $\mathbb{R}$ given by $f(x) = x^2$, and let $E = \{x \in \mathbb{R} \: -1 \leq x \leq 0 \}$  and $F = \{x \in \mathbb{R}: 0 \leq x \leq 1 \}$.Then $E \cap F = \{0\}$ and $f(E \cap F) = \{0\}$ while $f(E) = f(F) = \{ y \in \mathbb{R}: 0 \leq y \leq 1\}$. Hence $f(E \cap F)$ is a proper subset of $f(E) \cap f(F)$. Now delete $0$ from E and F.*  

The sets $E$ and $F$ with $0$ deleted are denoted $E' = \{ x \in \mathbb{R} : -1 \leq x < 0 \}$ and $F' = \{x \in \mathbb{R} : 0 < x \leq 1\}$, respectively. We still have the equality $f(E') = f(F') = \{ y \in \mathbb{R}: 0 < y \leq 1\} = f(E') \cap f(F')$. We also have $E' \cap F' = \emptyset$, and thus $f(E' \cap F') = \emptyset$, and $\emptyset = f(E' \cap F') \subseteq F(E') \cap f(F')$, since the empty set is a subset of all sets. 

\newpage

#### Section 3

*B. Exhibit a one-to-one correspondence between the set $O$ of odd natural numbers and $\mathbb{N}$*

The function $f(x) = \frac{x + 1}{2}, x\in \mathbb{N}$ maps the set of odd natural numbers, $O = \{2k - 1: k \in N\} \rightarrow \mathbb{N}$.

*D. If $A$ is contained in some initial segment of $\mathbb{N}$, use the well-ordering property of $\mathbb{N}$ to define a bijection of $A$ onto some initial segment of $\mathbb{N}$.*

If $A \neq \emptyset$ is a subset of some initial segment $\mathbb{N}$, by the well-ordering principle, there exists an $m \in A$ such that $m \leq k$ for all $k \in A$. A bijection $f$ can be defined by the mapping from set $A$ consisting of elements $\{a_1,a_2,...,a_k\}$ to elements of some initial segment $S_k = \{1,2,...,k\}$ as a set of ordered pairs $\{(a_1,1),(a_2,2),...,(a_k,k)\}$, such that $a_1 \leq a_2 \leq ... \leq a_k$ and clearly the corresponding elements in the pairs from set $S_k$, $1 \leq 2 \leq ... \leq k$. Here the number of elements in $A$ and $S_k$ are the same, which has a one-one correspondence $f: A \rightarrow S_k$ and the $R(f) = S_k$.

*F. Use the fact that every infinite set has a denumerable subset to show that every infinite set can be put into one-one correspondence with a proper subset of itself.*

By defintion, having a denumberable subset $\implies$ there exists a bijective function that maps a proper subset of an infinite set, $B$, onto $\mathbb{N}$. If we take infinite set $B = \{b_1,b_2,...,b_n,...\}$ and $B_1 = \{b_2,b_3,...,b_n,b_{n+1},...\}$, $B_1 \subseteq B$, we can create a one-one correspondence $f: B \rightarrow B_1$ defined by the set or ordered pairs $\{(b_n, b_{n+1}): n \in N\}$ which maps $B$ to $B_1 = B \setminus \{b_1\}$. 

*H. Show that if the set $A$ can be put into one-one correspondence with a set $B$, and if $B$ can be put into one-one correspondence with a set $C$, then $A$ can be put into one-one correspondence with $C$.*

If $A$ can be put into one-one correspondence with a set $B \implies$ there exists an injective function, $f$ from $A \rightarrow B$. This means that for $a,a' \in A$, and $b \in B$, $f(a) = f(a') = b \implies a = a'$. Similarly, if $B$ can be put into one-one correspondence with a set $B \implies$ there exists an injective function, $g$ from $B \rightarrow C$, and with $b,b' \in A$, $g(b) = g(b') = c \in C \implies b = b'$. By these properties, the composition of these two injective functions, $g \circ f (a) = g \circ f (a') \implies f(a) = f(a') \implies a = a'$ putting $A$ and $C$ in one-one correspondence.  

*I. Using induction on $n \in \mathbb{N}$, show that the initial segment determined by $n$ cannot be put into one-one correspondence with the initial segment determined by $m \in \mathbb{N}$, if $m < n$.*

Let $S_n = \{1,2,3,...,n\}$ be the initial segment determined by $n \in N$ and $S_m$ be the initial segment determined by $m \in N, m < n$. If $S_n$ can be put into one-one correspondence with $S_m \implies$ there exists and injection $f : S_n \rightarrow S_m$. For $n = 1$ we have $f : \{1\} \rightarrow S_m,\ m < 1$, but $S_m$ does not exist by definition for $m < 1$ implying the function is not valid for the case $n = 1$, $m < n$. For, the case $n = k + 1$, we again have a map $f: \{1,2,...,k+1\} \rightarrow \{1,...,m\},\ m < k + 1$ which implies a mapping of $k+1$ elements to $m < k+1$ elements $\implies$ there exists at least two elements $x,x' \in S_{k+1}$ for which $f(x) = f(x')$ and $x \neq x' \implies$ an injection does not exist between these sets. 

#### Section 4 

*C. Prove part (b) of Theorem 4.4, that is, Let $a \neq 0$ and $b$ be arbitrary elements of $\mathbb{R}$. Then the equation $a \cdot x = b$ has the unique solution $x = \frac{1}{a} b$*

Let $x_1$ be any solution to the equation, that is, $a \cdot x_1 = b$. By $(M4)$ we have that there is exists for each element $a \neq 0$ in $\mathbb{R}$ there exists an element $\frac{1}{a}$ such that $a(\frac{1}{a}) = 1$. Thus we have $(\frac{1}{a})ax_1= b(\frac{1}{a}) \implies 1 \cdot x_1 = b (\frac{1}{a}) \implies a \cdot x_1 = b$ has the unique solution $x_1 = \frac{b}{a}$.

*F. Use the argument in Theorem 4.7 to show that there does not exist a rational number $s$ such that $s^2 = 6.$*

If we assume that $s^2 = (\frac{p}{q})^2 = 6$, where $p, q \in \mathbb{Z}, q \neq 0$ and assume that $p$ and $q$ have no common integral factors, since $p^2 = 2 (3q^2) \implies$ that $p^2$, and $p$ is even for some $p = 2k$, $k \in \mathbb{N} \implies p^2 = 4k^2 = 2 (3q^2) \implies 2k^2 = 3q^2 \implies q^2$, and $q$ must be even, which is a contradiction of the assumption that $p$ and $q$ have no common integral factors, and thus a rational number $s$ such that $s^2 = 6$ does not exist.

*G. Modify the argument in Theorem 4.7 to shwo there there does not exists a ration number $t$ such that $t^2 = 3$.*

If we assume that $t^2 = (\frac{p}{q})^2 = 3$, where $p, q \in \mathbb{Z}, q \neq 0$ and assume that $p$ and $q$ have no common integral factors, we have $p^2 = 3q^3$ which implies that $p^2$ and $p$ are divisible by $3 \implies$ there exists $k \in \mathbb{N}$ such that $p = 3k \implies p^2 = 9k^2 = 3q^2 \implies 3k^2 = q^2$. This implies that $q^2$ is also divisible by $3 \implies q$ is divisible by $3$. This is again a contradiction of assumption $p$ and $q$ have no common integral factors, and thus a rational number $t$ such that $t^2 = 3$ does not exist.   

*H. If $\xi \in \mathbb{R}$ is irrational and $r \in \mathbb{R}$, $r \neq 0$, is rational, show that $r + \xi$ and $r\xi$ are irrational.*

If we take another rational number $c = \frac{a}{b},\ a,b \in \mathbb{Z}, b \neq 0$, and assume the contradiction that $r + \xi, r = \frac{p}{q},\ p,q \in \mathbb{Z}, q \neq 0$ is rational, that is $r + \xi = c$, we have $\xi = c - r = \frac{a}{b} - \frac{p}{q} = \frac{aq - bp}{bq}$ where $\frac{aq - bp}{bq}$ is a rational number, but clearly $\xi$ cannot not be equal to a rational number. Similarly for $r \xi = c \implies \xi = \frac{c}{r} = \frac{aq}{bp}$ where $\frac{aq}{bp}$ is clearly a rational number, again implying the contradiction that $\xi$ is equal to a rational number. Thus, by contradiction, $r + \xi$ and $r\xi$ must be irrational. 

#### Section 5

*B. If $n \in \mathbb{N}$, show that $n^2 \geq n$ and hence $\frac{1}{n^2} \leq \frac{1}{n}$.*

If $n \in \mathbb{N}$, then $n \geq 1 \implies n^2 \geq n$, since $n^2 = n \cdot n \cdot 1 \geq n \cdot 1 \implies n \geq \frac{n \cdot 1}{n \cdot 1} \implies n \geq 1$, a condition of $n$ being a natural number. 

*C. If $a \geq -1$, $a \in \mathbb{R}$, show that $(1 + a)^n \geq 1 + na$ for all $n \in \mathbb{N}$.*

Let $S$ be the set of all $n \in \mathbb{N}$ for which $(1 + a)^n \geq 1 + na$ is true. 
For $n = 1$ we have $(1 + a)^1 \geq 1 + (1)a = 1 + a$. For $k \in S$, we assume $(1 + a)^k \geq 1 + ka$
is true. For case $n = k + 1$, we have, using the binomial theorem,  
$$(1 + a)^{k + 1} = (1 + a)(1 + a)^k = (1 + a)\sum_{j = 0}^{k}{k \choose j}a^j = (1 + a)({k\choose0}a^0 + {k \choose 1}a^1 + ... + {k \choose k}a^k) = (1+a)(1 + ka + ... + a^k)$$
This implies, $(1 + a)^{k + 1} \geq (1 + a)(1 + ka) = 1 + ka + a + ka^2 = 1 + (k +1)a + ka^2 \geq 1 + (k+1)a$, since $k a^2 \geq 0$. Thus, $(1 + a)^{k + 1} \geq 1 + (k + 1)a$ holds, for $k + 1 \in S$. 

*F. Suppose that $0 < c < 1$. If $m \geq n,\ m, n \in \mathbb{N}$, show that $0 < c^m \leq c^n < 1$.*

By property 5.6(c), for $a,b,c \in \mathbb{R}$, if $a > b\ \text{and}\ c > 0$, then $ac > bc$. Applying this property here we have, $0 < c < 1 \implies 1 > c\ \text{and}\ c > 0 \implies c = 1 \cdot c > c \cdot c = c^2$, thus $0 < c^2 < c < 1 \implies 1 > c\ \text{and}\ c^2 > 0$, and $c^2 > c^3$, up to $c^k > c^{k+1}$, $k \in \mathbb{N}$. Thus for $m, n \in \mathbb{N}$, $m \geq n$, we have $0 < c^m \leq c^n < 1$.    

*G. Show that $n < 2^n$ for all $n \in \mathbb{N}$. Hence $(1/2)^n < 1/n$ for all $n \in \mathbb{N}$.*

Applying induction, for case $n=1$ we have true statement $1 < 2^1$. We assume the inequality is valid for $k \in \mathbb{N}$, and for case $n = k + 1$, we have $k + 1 < 2^{k + 1} = 2 \cdot 2^k$. For all $k \geq 1$ we have first, $k + 1 \leq k + k = 2k$, and since $2k \leq 2^{k + 1}$, i.e. $k \leq 2^k \implies k + 1 \leq 2^{k + 1}$. Since the inequality holds for $n = k + 1$, we assume it holds for all $n \in \mathbb{N}$.

*K. If $a,b \in \mathbb{R}$ and $b \neq 0$, show that $|a/b| = |a|/|b|$*
  
(i) For the case, $a \geq 0,\ b > 0$, $a \cdot 1/b \geq 0$, and we thus have $|a/b| = |a \cdot 1/b| = a/b = |a| \cdot |1/b|$, thus $a/b = |a|/|b|$.  
(ii) For the case, $a \geq 0,\ b < 0$, we have $a/b \leq 0\ \ \forall\ a,b$, thus $|a/b| = |a \cdot 1/b| = -(a/b) = a \cdot 1/-b$, and $a, -b \in \mathbb{P} \implies a \cdot 1/-b \geq 0$, thus $a/-b = |a|/|b|$.  
(iii) For the case, $a \leq 0,\ b < 0$, we have $a/b \geq 0,\ \forall\ a,b$, thus, $|a/b| = |a \cdot 1/b| = (a/b) = -a \cdot 1/-b$, thus $-a/-b = a/b = |a|/|b|$.  
(iiii) For the case, $a \leq 0,\ b > 0$ we have $a/b \leq 0\ \  \forall\ a,b$, thus, $|a/b| = -(a/b) = -a/b = -a/|b| = |a|/|b|$.

*L. If $a,b \in \mathbb{R}$, then $|a + b| = |a| + |b|$ if and only if $ab \geq 0$.*

$ab \geq 0 \implies a,b \in \mathbb{P}\ \ \text{or} -a, -b \in \mathbb{P}$. For the case, $a,b \in \mathbb{P}$, we have $|a + b| = a + b = |a| + |b|\ \  \forall\ a,b \in \mathbb{P}$. For the case, $-a,-b \in \mathbb{P}$, we have, $|a + b| = -(a + b) = -a - b = |a| + |b|$. 

#### Section 6 
*B. Show that if a subset $S$ of $\mathbb{R}$ contains an upper bound, then this upper bound is the supremum of $S$.*

Let the upper bound of $S \subseteq \mathbb{R}$ be $u \in \mathbb{R}$, then assume for all $s \in S$, $u \geq s$. If $s \leq v\ \ \forall s \in S$, then $u \leq v$, then there is another number that satisfies the supremum and $u$ is not a supremum of $S$.

*C. Give an example of a set of rational numbers which is bounded but does not have a rational supremum.*

Take the set $S = \{ x \in \mathbb{Q}: x^2 < 3 \}$, bounded above by the irrational $\sqrt(3)$, where $\mathbb{Q} = \{\frac{m}{n} : m,n \in \mathbb{Z}, n \neq 0\}$.

*G. If $S$ is a bounded set in $\mathbb{R}$ and if $S_0$ is a non-empty subset of $S$, then show that $\text{inf}\ S \leq \text{inf}\ S_0 \leq \text{sup}\ S_0 \leq \text{sup}\ S$*

By definition, $S_0 \subseteq S \implies$ there exists either, an element in $S$ that is not in $S_0$ or $S_0$ exhausts all of $S$ (i.e. they are equal). 
Let $u = \text{inf}\ S \implies u \leq s \ \ \forall s \in S$ and $s \in S_0$. Let $u_0 = \text{inf}\ S_0 \implies u_0 \leq s\ \ \forall s \in S_0 \subseteq S \implies u \leq u_0 \implies \text{inf }\ S \leq \text{inf}\ S_0$. 
Let $w = \text{sup}\ S \implies w \geq s \forall s \in S$ and $s \in S_0$. Let $w_0 = \text{sup}\ S_0 \implies w_0 \geq s\ \ \forall s \in S_0$, but not necessarily for all $s \in S$. This implies $w \geq w_0\ \ \forall s \in S$. Since by definition $\text{sup}\ S_0 \geq \text{inf}\ S$, and since $w \geq w_0 \implies u \leq u_0 \leq w_0 \leq w \Leftrightarrow \text{inf}\ S \leq \text{inf}\ S_0 \leq \text{sup}\ S_0 \leq \text{sup}\ S$.

*H. Let $X$ and $Y$ be non-empty sets and let $f: X \times Y \rightarrow \mathbb{R}$ have a bounded range in $\mathbb{R}$. Let, $f_1(x) = \text{sup} \{f(x,y): y \in Y\}$, and $f_2(y) = \text{sup} \{f(x,y): x \in X\}$. Establish the Principle of Iterated Suprema: $\text{sup} \{f(x,y): x \in X, y \in Y\} = \text{sup} \{f(x,y): y \in Y\} = \text{sup} \{f(x,y): x \in X\}$.*

Let $u = \text{sup}\ \{f(x,y): x \in X, y \in Y\} \implies u \geq f(x,y)\ \ \forall f(x,y)$ where $x \in X, y \in Y$. This implies that $f_1(x) \leq u \ \forall y \in Y$. Conversely, let $u_0 = \text{sup}\ f_1(x) = \text{sup}\ \{f(x,y): y \in Y\}$. This implies $u_0 \geq u \ \ \forall x \in X, y \in Y$. 
This implies that $u = u_0$, and thus $\text{sup}\ \{f(x,y): x \in X, y \in Y\} = f_1(x) = \text{sup}\ \{f(x,y): y \in Y\}$. By extension the same argument hold for $\text{sup}\ \{f(x,y): x \in X, y \in Y\} = \text{sup}\ f_2(y) = \text{sup} \{f(x,y): x \in X\}$.

*J. Let $X$ be a non-empty set and let $f: X \rightarrow \mathbb{R}$ have a bounded range in $\mathbb{R}$. If $a \in \mathbb{R}$, show that:*
*$\text{sup} \{a + f(x): x \in X\} = a + \text{sup} \{f(x): x \in X\}$*, and
*$\text{inf} \{a + f(x): x \in X\} = a + \text{inf} \{f(x): x \in X\}$*.

Let $u = \text{sup} \{a + f(x): x \in X\} \implies u \geq a + f(x)\ \ \forall\ x \in X \implies u -a \geq f(x)\ \ \forall x \in X \implies \text{sup} \{f(x): x \in X\} = u-a$. This implies that $u = a + \text{sup} \{f(x): x \in X\}$, and thus $\text{sup} \{a + f(x): x \in X\} = a + \text{sup} \{f(x): x \in X\}$.

Using the same argument, let $w = \text{inf} \{a + f(x): x \in X\} \implies w \leq a + f(x)\ \ \forall\ x \in X \implies w -a \leq f(x)\ \ \forall x \in X \implies \text{inf} \{f(x): x \in X\} = w-a$. This implies that $w = a + \text{inf} \{f(x): x \in X\}$, and thus $\text{inf} \{a + f(x): x \in X\} = a + \text{inf} \{f(x): x \in X\}$. 

*K. Let $X$ be a non-empty set and let $f$ and $g$ be defined on $X$ have a bounded ranges in $\mathbb{R}$. Show that:*
*$\text{inf}\ \{f(x): x \in X\} + \text{inf}\ \{g(x): x \in X\} \leq \text{inf}\ \{f(x) + g(x): x \in X\} \leq \text{inf}\ \{f(x): x \in X\} + \text{sup}\ \{g(x): x \in X\} \leq \text{sup}\ \{f(x) + g(x): x \in X\} \leq \text{sup}\ \{f(x): x \in X\} + \text{sup}\ \{g(x): x \in X\}$*


#### Section 7
*F.*
*G.*
*K.*

