---
title: 'Math 4317 (Prof. Swiech, S''18): HW #2'
author: "Peter Williams"
date: "2/27/2018"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Section 8
*D. If $w_1$ and $w_2$ are strictly positive, show that the definition, $(x_1,x_2) \cdot (y_1,y_2) = x_1 y_1 w_1 + x_2 y_2 w_2$ , yields an inner product on $\mathbb{R}^2$, generalize this for $\mathbb{R}^p$ .*

Checking the properties of inner products, we have, based on definition above,  $(i)\ x \cdot x \geq 0$, since $(x_1,x_2)(x_1,x_2) = w_1x_1^2 + w_2x_2^2 \geq 0$, since $w_1, w_2 > 0$, and $x_i^2 > 0$, $i = 1,2$. For $x \in \mathbb{R}^p$, we have $x \cdot x = \sum_{j = 1}^{p}w_jx_j^2 \geq 0$, since each element in the summation $w_i, x_i^2 > 0$. 
For property $(ii)$, we have $x \cdot x = 0$, if and only if $x=0$. In this case, since $w_1,w_2 > 0$, $w_1x_2^2 + w_2x_2^2 = 0$, when $x_1^2$ and $x_2^2$ equal zero, that is when $x = 0$. This holds for $x \in \mathbb{R}^p$, since for $w_i > 0,\ \ i = 1,...,p$ we have $\sum_{j=1}^{p}w_jx_j^2 = 0$, only when each element $w_ix_i2 = 0$, since each element is greater than or equal to zero. 
For property $(iii)$, we show $x \cdot y = y \cdot x$ since $x \cdot y = w_1 x_1 y_1 + w_2 x_2 y_2 = w_1 x_1 y_1 + w_2 x_2 y_2 = w_1 y_1 x_2 + w_2 y_2 x_2 = y \cdot x$. Extending to $x \in \mathbb{R}^p$, we have again, by commutative property, $x \cdot y = \sum_{j=1}^{p} w_jx_jy_j = \sum_{j=1}^{p} w_jy_jx_j = y \cdot x$.
Property $(iv)$, $x \cdot (y + z) = x \cdot y + x \cdot z,\ x,y,z \in \mathbb{R}^p$. In this case we have $\sum_{j=1}^{p}w_jx_j(y_j + z_j) = \sum_{j=1}^{p}w_jx_jy_j + w_jx_jz_j =\sum_{j=1}^{p}w_jx_jy_j + \sum_{j=1}^{p} w_jx_jz_j = x\cdot y + x \cdot z$, which clearly holds for base case, $p=2$ as well.
For property $(v)$, we have $(ax)\cdot y = x \cdot (ay),\ a \in \mathbb{R}$. We have $(ax)\cdot y  = \sum_{j=1}^{p}w_jax_jy_j = a\sum_{j=1}^{p}w_jx_jy_j = a(x \cdot y) = \sum_{j=1}^{p}w_jx_jay_j = x \cdot (ay)$. Since all five properties are satisfied, an inner product is yielded here. 

*E. $(x_1,x_2)\cdot(y_1,y_2) = x_1 y_1$ is not an inner product on $\mathbb{R}^2$. Why?*

By property $(ii)$, i.e. $x \cdot x = 0$ if and only if $x = 0$, the definition above, $(x_1,x_2)\cdot(y_1,y_2) = x_1 y_1 = 0 \Leftrightarrow x =0$, however, we can't say $x = 0$, since in this case if $x_1 y_1 = 0 \implies x_1 = 0$, but we don't have information about $x_2$, or $x_i, i  = 3,...,p$, for $x \in \mathbb{R}^p$. Thus for this operation $x \cdot x = 0$ does not necessarily mean $x = 0$.

*F. If $x = (x_1,x_2,...,x_p) \in \mathbb{R}^p$, define $||x||_1$ by $||x||_1 = |x_1| + |x_2| + ... + |x_p|$. Prove that $x \rightarrow ||x||_1$ is a norm on $\mathbb{R}^p$.*

(i) $||x||_1 \geq 0$?. Since $|x_j| \geq 0\ \forall j \implies ||x|| = \sum_{j=1}^{p}|x_j| \geq 0$ by definition of the absolute value. 
(ii) $||x||_1 = 0$ if and only if $x = 0$?. $||x|| = \sum_{j=1}^{p}|x_j| = 0 \implies x_j = 0\ \forall j \implies x = 0$.
(iii) $||ax||_1 = |a|||x||\ \forall a \in \mathbb{R},\ x \in V$? When $a \geq 0$, and $x_j \geq 0$ or $a < 0$ and $x_j < 0$, $||ax_j|| = a x_j = |a||x_j|$. For the case $a < 0$ and $x_j \geq 0$ or $a \geq 0$ and $x_j < 0$, we have $||a_x)j||  = |ax_j| = (-1)a x_j$ or $a (-1) x_j = a |x_j| = |a||x_j|$.
(iv) $||x + y||_1 \leq ||x|| + ||y||$ for $x, y \in \mathbb{R}^p$?. $||x + y|| = |x_1 + y_1| + |x_2 + y_2| + ... + |x_p + y_p|$. By the triangle inequality, $|x_j + y_j| \leq |x_j| + |y_j|$ for all $j$. Therefore $|x_1 + y_1| + |x_2 + y_2| + ... + |x_p + y_p| \leq |x_1| + |x_2| + ... + |x_p| + |y_1| + |y_2| + ... + |y_p| = ||x|| + ||y||$. Thus $||x||_1$ is a norm on $\mathbb{R}^p$. 

*G.If $x = (x_1,x_2,...,x_p) \in \mathbb{R}^p$, define $||x||_{\infty}$ by $||x||_{\infty} = \text{sup} \{ |x_1| + |x_2| + ... + |x_p| \}$. Prove that $x \rightarrow ||x||_{\infty}$ is a norm on $\mathbb{R}^p$.*

(i) $||x||_{\infty} \geq 0$? Since $|x_j| \geq 0\ \forall j \implies ||x||_{\infty} = \text{sup} \{ |x_1| + |x_2| + ... + |x_p| \} \geq 0$ since each element in the set is greater than zero.
(ii) $||x||_{\infty} = 0$ if and only if $x = 0$?. Since each element in the set $\{ |x_1| + |x_2| + ... + |x_p| \}$ is greater than or equal to zero, $||x||_{\infty} = 0$ if and only if $x_j = 0$ for all $j$, which implies $x = 0$.
(iii) $||ax||_{\infty} = |a|||x||_{\infty}\ \forall a \in \mathbb{R},\ x \in V$? $||ax||_{\infty} = \text{sup} \{|ax_1| + |ax_2| + ... + |ax_p| \}$, and as shown in 8.F $|ax_j| = |a||x_j|$, which implies $||ax||_{\infty} = \text{sup} \{|a||x_1| + |a||x_2| + ... + |a||x_p| \} = |a| \text{sup}\{|x_1| + |x_2| + ... + |x_p|\} = |a|||x||_{\infty}$, since $|a|,|x_j| > 0$.
(iv)$||x + y||_{\infty} \leq ||x||_{\infty} + ||y||_{\infty}$ for $x, y \in \mathbb{R}^p$?. Again, by the triangle inequality, $|x_j + y_j| \leq |x_j| + |y_j|$ for all $j$. Therefore $\text{sup} \{ |x_1 + y_1| , |x_2 + y_2| , ... , |x_p + y_p| \} \leq \text{sup} \{ |x_1| + |y_1| , |x_2| + |y_2| , ... , |x_p| + |y_p| \}$. If we take $u_x = \text{sup}\{|x_j|\}$,$u_y = \text{sup}\{|y_j|\}$. $u_x + u_y \geq |x_j| + |y_j|$ for all $j \implies \text{sup}\{|x_j|\} + \text{sup}\{|y_j|\} = \text{sup}\{|x_j| + |y_j|\} \implies ||x+y||_{\infty} \leq ||x||_{\infty} + ||y||_{\infty}$. Thus, $||x||_{\infty}$ is a norm on $\mathbb{R}^p$. 

*H. In the set $\mathbb{R}^2$, describe the sets:* 

$S_1 = \{x \in \mathbb{R}^2 : ||x||_1 < 1\}$. $||x||_1 = \sqrt{x_1^2 + x_2^2} < 1$ describes and open circle consisting of points less than 1 in all directions from the origin, satisfying the inequality, $\sqrt{x_1^2} < \sqrt{ 1 - x_2^2}$.
$S_{\infty} = \{x \in \mathbb{R}^2 : ||x||_{\infty} < 1 \}$, where $||x||_{\infty} = \text{sup}\{|x_1|, |x_2|\}$, is a dense open box with vertices at $(1,1), (-1,1), (-1,-1), (1,-1)$ with $-1 < x_1 < 1$, and $-1< x_2 < 1$.

*P. If $x,y$ belongs to $\mathbb{R}^p$, show that $||x+y||^2 = ||x||^2 + ||y||^2$ if and only if $x \cdot y = 0$.*

$||x + y||^2 = (x + y)\cdot(x + y) = x \cdot x + y \cdot x + x \cdot + y + y \cdot y  = ||x||^2 + 2 x\cdot y + ||y||^2$, and $2 x \cdot y = 0$ if and only if $x \cdot y = 0$, thus, in order for $||x+y||^2 = ||x||^2 + ||y||^2$ to hold, $x \cdot y$ must equal zero. 

*Q. A subset $K$ of $\mathbb{R}^p$ is said to be convex if, whenever, $x, y \in K$, and $t$ is a real number such that $0 \leq t \leq 1$, then the point $tx + (1-t)y$ also belongs to $K$. Show that $K_1,K_2, K_3$ are convex, but that $K_4$ is not.*

1) $K_1 = \{x \in \mathbb{R}^2 : ||x|| < 1\}$. Let $x, y \in K_1$, then $||tx + (1-t)y|| \leq ||tx|| + ||(1 - t)y|| = |t|||x|| + |(1-t)|||y||$, and since $||x|| \leq 1$ and $||y|| \leq 1$, it implies $|t|||x|| + |(1-t)|||y|| \leq |t|(1) + |(1 -t)|(1) = t + 1 - t = 1 \implies tx + (1 - t)y \in K_1$.
2) For $K_2  = \{(\xi, \eta) \in \mathbb{R}^2 : 0 < \xi < \eta \}$. Let $x = (x_1, x_2), y = (y_1, y_2) \in K_2 \implies 0 < x_1 < x_2$ and $0 < y_2 < y_2$, for the point $tx + (1- t)y$ to belong in $K_2$ it implies for $t \in [0,1] \implies 0 < tx_1 < tx_2$, and $0 < (1-t)y_1 < (1-t)y2$. Adding these inequalities, we have for $tx + (1- t)y$, $0 < tx_1 + (1 - t)y_1 < tx_2 + (1 - t)y_2 \implies tx + (1- t)y \in K_2$.
3) Similarly for $K_3  = \{(\xi, \eta) \in \mathbb{R}^2 : 0 \leq \xi \leq \eta \leq 1 \}$, $x, y \in K_3$, $t \in [0,1]$, we have $0 \leq x_1 \leq x_2 \leq 1$ and $0 \leq y_1 \leq y_2 \leq 1 \implies 0 \leq tx_1 \leq tx_2 \leq t$ and $0 \leq (1-t)y_1 \leq (1-t)y_2 \leq (1-t)$, again adding the inequalities, we have $0 \leq tx_1  + (1- t)y_1\leq tx_2 + (1-t)y_2 \leq t + (1 - t) = 1 \implies tx + (1-t)y \in K_3$.
4) For $K_4 = \{x \in \mathbb{R}^2 : ||x|| = 1\}$. Like in $K_1$, $x, y \in K_4$, then $||tx + (1-t)y|| = ||tx|| + ||(1 - t)y|| = |t|||x|| + |(1-t)|||y||$, and since $||x|| \leq 1$ and $||y|| \leq 1$, it implies $|t|||x|| + |(1-t)|||y|| \leq |t|(1) + |(1 -t)|(1) = 1$. This equality could hold in some cases where $||x|| = 1$, e.g. $(1,0), (0,1)$, but does not hold for all points, and thus $K_4$ is not convex.  

#### Section 9
*B. Justify assertions from 9.2(c):*  

(i) Denote $x = (x_1,x_2)$ the set $G =\{x \in \mathbb{R}^2 : x_1^2 + x_2^2 < 1 \}$ which is equivalent to $G =\{x \in \mathbb{R}^2 : \sqrt{x_1^2 + x_2^2} = ||x|| < 1 \}$. Let $\varepsilon = 1 - ||x|| > 0$. Take $y \in \mathbb{R}^2$ such that $||y - x|| < 1$, then, by triangle inequality $||y|| = ||y - x + x|| \leq ||y - x|| + ||x|| < \varepsilon + ||x|| = 1 - ||x|| + ||x|| = 1 \implies y \in G$, and thus $G$ is open.  
(ii) Take $x = (x_1,x_2)$, and $H = \{x \in \mathbb{R}^2 : 0 < ||x||^2 < 1\}$. Take $y \in \mathbb{R}^2$ such that $||y-x|| < \varepsilon$, where $\varepsilon = \text{inf}\{||x||, 1 - ||x||\}$. Again $||y|| = ||y - x + x|| \leq ||y - x|| + ||x|| < \varepsilon + ||x|| = 1 - ||x|| + ||x|| = 1 \implies ||y|| < 1$. With $||x- y|| < \varepsilon \implies ||x|| - ||y|| < \varepsilon  \implies ||y|| > ||x|| - \varepsilon \implies ||y|| > ||x|| - ||x|| \implies ||y|| > 0 \implies y \in H$, and $H$ is open.  
(iii) $F = \{x \in \mathbb{R}^2 : ||x||^2 \leq 1\}$. The complement of $F$, $F^c = \{x \in \mathbb{R}^2: ||x||^2 > 1\}$ is open, since for $\varepsilon = ||x|| -1 > 0$, $y \in \mathbb{R}^2$, $||x - y|| > ||x|| - ||y|| < 1 \implies ||x|| - \varepsilon < ||y|| \implies 1 < ||y|| \implies y \in F^c \implies F^c$ is open, and its complement $F$ must be closed as a result.  

*D. What are the interior, boundary, and exterior points in $\mathbb{R}$ of the set $[0,1)$. Conclude that it is neither open nor closed.*  

Let $A = [0,1)$. The interior points of $A$ consist of points in the open interval $(0,1)$ which is entirely contained in $A$. The boundary points of $A$ are the points $0$ and $1$. Since neighborhoods around the point $1$ and $0$ contain both points in $A$ and in its complement $A^c$. The exterior points of $A$ are points in the set consisting of the union of the intervals $(-\infty, 0) \cup [1,\infty)$. $A$ is not closed, since it does not contain the boundary point, $1$. $A$ is not open, by construction, since it is the union of an open and closed set or interval. 

\newpage

*G. Show that a subset of $\mathbb{R}^p$ is open if and only if it is the union of a countable collection of open balls.*  

Let $U \subseteq \mathbb{R}^p$ be open, and $\{x_n : n \in \mathbb{N} \}$ be the set of all rational points in $U$. Since $U$ is open $\implies$ there exists $r > 0$, such that each point $x_n$ can be contained in the open ball $B_r(x_n) = \{y \in \mathbb{R}^p : |y - x_n| < r\}$, such that $B_r(x_n) \subseteq U \implies \cup_{n \in \mathbb{N}} B_r(x_n) \subseteq U$ if we choose $r$ large enough.

Let $U \subseteq \mathbb{R}^p$ be a countable collection of open balls $\implies$ for every rational point $x_n$, there exists an open ball $B_r(x_n),\ r > 0$, where $x_n \in B_r(x_n) \implies U \subseteq \cup_{n \in \mathbb{N}} B_r(x_n)$. Which implies $U = \subseteq \cup_{n \in \mathbb{N}} B_r(x_n)$.

*I. Show every closed subset of $\mathbb{R}^p$ is the intersection of a countable collection of open sets.*  

If $U \subseteq \mathbb{R}^p$ is a closed subset, i.e. for $y \in \mathbb{R}^p,\ x \in U,\ r_c > 0,\ U = \{y : ||x- y|| \leq r_c\}$, take the open set $\{y : ||x - y|| > r_c + 1/n\},\ n \in \mathbb{N} \implies x \in U \subseteq \cap_{n \in N} \{y : ||x-y|| < r_c + 1/n\}$.

If $x \notin U \implies x \in \mathbb{R}^p \setminus U \implies x \in \{y : ||x - y|| > r_c\} \implies x \notin \{y : ||x - y|| > r_c + 1/n\},\ n \in \mathbb{N} \implies x \in \mathbb{R}^p \setminus \cap_{n \in N}\{y : ||x - y|| > r_c + 1/n\} \implies \mathbb{R}^p \setminus U \subseteq \cap_{n \in N}\{y : ||x - y|| > r_c + 1/n\} \implies \cap_{n \in N}\{y : ||x - y|| > r_c + 1/n\} \subseteq U$. Thus $U = \cap_{n \in N}\{y : ||x - y|| > r_c + 1/n\}$.

*J. If $A$ is any subset of $\mathbb{R}^p$, let $A^0$ denote the union of all open sets which are contained in $A$; the set $A^0$ is called the interior of $A$ Note that $A^0$ is an open set; (i) prove that it is the largest open set contained in $A$, also prove: (ii) $A^0 \subseteq A$, (iii) $(A^0)^0 = A^0$, (iv) $(A \cap B)^0 = A^0 \cap B^0$, and (v) $(\mathbb{R}^p)^0 = \mathbb{R}^p$. Also give and example to show $(A \cup B)^0 = A^0 \cup B^0$ may not hold.*

(i) Take $U$ as any open set contained in $A$. $A^0$ by definition is a union of all these sets, thus each $U \subseteq A^0 \implies A^0 \subseteq A$.  
(ii) By definition $(A^0)^0 \subseteq A^0$, and since $(A^0)^0$ is by definition, the union of all open sets in $A^0 \implies A^0 \subseteq (A^0)^0 \implies A^0 = (A^0)^0$.  
(iii) $(A \cap B)^0$ is the union of all open sets in $A \cap B \implies (A \cap B)^0 \subseteq A \cap B \implies (A \cap B)^0 \subseteq A$ and $(A \cap B)^0 \subseteq B$. Since $A^0, B^0$ contain all their open sets $\implies (A \cap B)^0 \subseteq A^0$ and that  $(A \cap B)^0 \subseteq B^0 \implies (A \cap B)^0 \subseteq A^0 \cap B^0$.
In the other direction, $A^0 \subseteq A, B^0 \subseteq B \implies A^0 \cap B^0 \subseteq (A \cap B)$, and since $A^0 \cap B^0$ is the intersection of two open sets, it follows that $A^0 \cap B^0 \subseteq (A \cap B)^0$. This implies $(A \cap B)^0 = A^0 \cap B^0$.  
(iv) $\mathbb{R}^p$ is an open set, and equals the collection of all open sets in it, which implies $\mathbb{R}^p = (\mathbb{R}^p)^0$.
*Give an example that $(A \cup B)^0 = A^0 \cup B^0$ may not hold.*  
If we take $A = [0,1], B = [1,2] \implies A^0 = (0,1), B^0 = (1,2) \implies A^0 \cup B^0 = (0,1) \cup (1,2),\ (A \cup B)^0 = (0,2) \implies \{1\} \in (A \cup B)^0,\ \{1\} \notin A^0 \cup B^0$. 

*K.Prove that a point belongs to $A^0$ if and only if it is an interior point of $A$.*  
Let $x$ be an interior point of $A \implies x$ can be contained in an open set in $A$, and since $A^0$ is the union of all open sets in $A \implies x \in A^0$.
Let $x$ belong to $A^0 \implies$ belongs to an open set that is contained in $A^0 \implies x$ is an interior point in $A^0 implies$ x in an interior point of $A$.

*L. If $A$ is any subset of $\mathbb{R}^p$, let $A^0$ denote the intersection of all closed sets which are containing $A$; the set $A^{-}$ is called the closure of $A$ Note that $A^{-}$ is an closed set; (i) prove that it is the smallest closed set containing $A$, prove that : (ii) $A \subseteq A^{-}$, (iii) $(A^{-})^{-} = A^{-}$, (iv) $(A \cup B)^{-} = A^{-} \cup B^{-}$, and (v) $\emptyset^{-} = \emptyset$*  

(i) Since $A^{-}$ is an intersection of all closed sets containing $A$, including the smallest closed set containing $A$, $A^-$ must be the smallest closed set containing $A$. This implies that a closed set $A \subseteq A^-$.    
(ii) Since $A^-$ is closed the smallest closed set that contains $A^-$ is $A^- \implies A^- \supseteq (A^-)^-$ and $A^- \subseteq (A^-)^- \implies A^- = (A^-)^-$.  
(iii) Let point $x \in (A \cup B)^- = A^- \cup B^- \implies x$ belongs to the smallest closed set containing A or B $\implies x \in A^-$ or $x \in B^- \implies x \in A^- \cup B^-$.  
(iv) Since $\emptyset$ is closed and contains no elements, the smallest losed set containing $\emptyset$ is $\emptyset^- \implies \emptyset^- = \emptyset$.  
*Give an example to show that $(A \cap B)^- = A^- \cap B^-$ may not hold.*  
Take $A = [0,1], B = (1,2]$, thus $(A \cap B) = \emptyset = (A \cap B)^-, A^- = [0,1], B^- = [1,2]$ and $A^- \cap B^- = \{1\} \neq (A \cap B)^-$.  

*M. Prove that a point belongs to $A^{-}$ if and only if it is either and interior or boundary point of $A$.*  

Let $x \in A^- \implies x$ belongs to the smallest closed set that contains $A \implies$ a neighborhood of $x$ is either entirely in $A$ or partly in $A$ and $A^c \implies x$ is either an interior or boundary point.

Let $x$ be an interior or boundary point of $A \implies$ any neighborhood of $x$ is either contained in $A$ and $A^c \implies x$ is either in $A$ or in a closed set containing $A$, i.e. $x \in A^-$.

#### Section 10
*C. A point $x$ is a cluster point of a set $A \subseteq \mathbb{R}^p$ if and only if every neighborhood of $x$ contains infinitely many points of $A$.*  
Let $x$ be a cluster point of $A \subseteq \mathbb{R}^p \implies$ there exists and element $a_n \in A$ such that $a_n \neq x$, $0 < ||x - a_n|| < \frac{1}{n}, n \in \mathbb{N} \implies$ there exists an element $a_{n+1} \in A$, such that $0 < ||x - a_{n+1}|| < \frac{1}{n+1}$ such that $a_n \neq a_{n+1}$ etc. which implies that is there is always an element of $A$ that satisfy this property that implies every neighborhood of a point $x$ contains infinitely many points.

*D. Let $A = \{\frac{1}{n} : n \in \mathbb{N} \}$. Show that every point of $A$ is a boundary point in $\mathbb{R}$, but that $0$ is the only clustter point of $A$ in $\mathbb{R}^p$.*  

Take $z >0, z \in \mathbb{R}$. By the completeness of $\mathbb{R}$, and properties of rational numbers, we have a number $\frac{1}{n}$ such that $0 < \frac{1}{n} < z, n \in \mathbb{N}$. Then for each point $x = \frac{1}{n}, n \in \mathbb{N}$, the neighborhood of $x$ consists of only the point $x \in A$, and points in the set $\{y \in \mathbb{R} : \frac{1}{n+1} < y < \frac{1}{n}\} \cup \{y \in \mathbb{R} :  \frac{1}{n} < y < \frac{1}{n-1}\}$, but this implies $y \notin A \implies y \in A^c \implies x$ is a boundary point. 

Since for $n \in \mathbb{N}$, the point $0$, is the only point in $A$ for which the property $0 < ||0 - \frac{1}{n+1}|| < \frac{1}{n} \implies 0 < ||0 - \frac{1}{n+2}|| < \frac{1}{n+1}$ and so on holds, which implies $0$ is the only cluster point in $A$.

*E. Let $A,B$ be subsets of $\mathbb{R}^p$ and let $x$ be a cluster point in $A \cap B \in \mathbb{R}^p$. Prove that $x$ is a cluster point of both $A$ and $B$.* 

Let $x$ be a cluster point in $A \cap B \subseteq B, A \cap B \subseteq A \implies$ there exists and open set in $A \cap B$ that contains $x$ and a point distinct from $x \implies$ there exists and open set in $A$ that contains $x$ and a point distinct from it, and the same holds for $B \implies$ $x$ is a cluster point of $A$ and $B$.

*F.Let $A,B$ be subsets of $\mathbb{R}^p$ and let $x$ be a cluster point in $A \cup B \in \mathbb{R}^p$. Prove that $x$ is a cluster point of either $A$ or $B$.*  

Let $x$ be a cluster point in $A \cup B \subseteq B \implies$ there exists an open set in $A$ or $B$ that contains $x$ and a point distinct from $x \implies$ 
either $A$ contains $x$ and its neighborhood containing at least another point distinct from $x$, or $B$ contains $x$ and its neighborhood containing at least one point distinct from $x \implies x$ is a cluster point of either $A$ or $B$.

*G. Show that every point in the Cantor set $F$ is a cluster point of both $F$ and the complement of $F$,$F^c$.*  

The Cantor set, $F$ by definition, is constructed by the intersection of sets $F_n, n \in \mathbb{N}$, where each set $F_n$ is constructed by the union of closed intervals, of the form $[\frac{k}{3^n}, \frac{k+1}{3^n}] \implies$ points in $F$ belonging to all intervals $F_n, n \in \mathbb{N} \implies$ these points are all boundary points of $F$, examples including $0, \frac{1}{3}, \frac{2}{3}, 1$. Neighborhoods around these boundary points include a point in $F$ and its complement $F^c \implies$ for $n \in \mathbb{N}$, and then the Cantor set $F$ consists of only boundary points which implies every point of $F$ is a cluster point of both $F$ and $F^c$.  

\newpage
#### Section 11  

*A. Show directly from the definition (i.e. with using the Heine-Borel Theorem) that the open ball given by $\{(x,y): x^2 + y^2 < 1\}$ is not compact in $\mathbb{R}^2$.*  
Let $H = \{(x,y): x^2 + y^2 < 1\}$ and let $G_n = \{(x,y): x^2 + y^2 < 1 - \frac{1}{n}\}$ so that $G^{'}= \{G_n: n \in \mathbb{N}\}$ be a collection collection of these open sets in $\mathbb{R}^2$ whose union contains $H$. If $\{G_{n_1},...,G_{n_k}\}$ is a finite subcollection of $G^{'}$, and $M = \text{sup}\{n_1,...,n_k\} \implies G_{n_j} \subseteq G_M,\ j = 1,...,k \implies G_M = \cup_{j=1}^{k} G_{n_j}$, but the point $(x,y)$ satisfying $x^2 + y^2 < 1 - \frac{1}{M}$ does not belong to $G_M \implies (x,y) \notin \cup_{j=1}^{k} G_{n_j} \implies$ no finite union of the sets $G^{'}$ contain $H \implies H$ is not compact.

*B. Show directly that the entire space $\mathbb{R}^2$ is not compact.*  
Let $H = \{(x,y) \in \mathbb{R}^2\}$, $G_n = \{(x,y): x^2 + y^2 < n^2\}$, and $G^{'}= \{G_n: n \in \mathbb{N}\}$ be a collection of these open sets in $\mathbb{R}^2$ whose union contains $H$. If $\{G_{n_1},...,G_{n_k}\}$ is a finite subcollection of $G^{'}$, and $M = \text{sup}\{n_1,...,n_k\} \implies G_{n_j} \subseteq G_M,\ j = 1,...,k \implies G_M = \cup_{j=1}^{k} G_{n_j}$, but the point $(x,y)$ satisfying $x^2 + y^2 < M^2$ does not belong to $G_M \implies (x,y) \notin \cup_{j=1}^{k} G_{n_j} \implies$ no finite union of the sets in $G^{'}$ can contain $\mathbb{R}^2$.  

*C. Prove directly that if $K$ is compact in $\mathbb{R}^p$ and $F \subseteq K$ is a closed set, then $F$ is compact in $\mathbb{R}^p$*  
If $K$ is compact in $\mathbb{R}^p$ and $F$ is a closed subset of $K \implies$ there exists a finite collection of open sets $G^{'} = \{G_{\alpha}\}$ whose union covers $K$, and further, contains $F$. Since the complement of closed $F$, namely, $F^c$ must be open $\implies$, the union of the open set $F^c$ and collection of open sets $G^{'}$ is a finite collection of sets that form a covering for $K$. Since $K$ is compact, and $F^c \cup G^{'}$ is finite $\implies G^{'}$ is a union of a finite collection of open sets containing $F \implies F$ is compact. 

*D. Prove that if $K$ is a compact subset of $\mathbb{R}$, then $K$ is compact when regarded as a subset of $\mathbb{R}^p$.*  
If $K$ is compact $\implies$ that is $K$ is covered by a collection of open sets, $G$, then it is contained by a finite number of the sets in $G$. Let $G^{'}$ be an open subset of $\mathbb{R}^2$ such that $G = G^{'} \cap \mathbb{R} \implies G^{'} \subseteq \mathbb{R}^2$ is a union of finite open sets, thus $K$ is compact in regards to being a subset of $\mathbb{R}^2$.

*G. Prove the Canton Intersection Theorem by selecting a point $x_n$ from $F_n$ and then applying the Bolzano-Weierstrass Theorem 10.6 to the set $\{x_n: n \in \mathbb{N}\}$.*   
If $x_n \in F_n, n \in \mathbb{N} \implies$ there exists at least one point in the set of possible $x_n$ that is a common point among the sets $F_n$, and by construction that each set $F_n$ is bounded and closed. By Bolzano-Weierstrass, every bounded infinite subset of $\mathbb{R^p}$ has a cluster point. This implies that if there is at least one $x_n$ common among, these sets, and that there is a cluster point $x \in F_n$ which belongs to all sets $F_k, k \in \mathbb{N}$.

*H. If $F$ is closed in $\mathbb{R}^p$ and if $d(x,F) = \text{inf}\{||x-z||: z \in F\} = 0$, then $x$ belongs to $F$.*   
$d(x,F) = \text{inf}\{||x - z||: z \in F\} = 0 \implies x=z,\ z \in F$ or there exists $n \in \mathbb{N}$ such that $0 < ||x - z|| = ||z-x|| < \frac{1}{n} \implies x,z$ are cluster points of $F \in \mathbb{R}^p \implies x \in F$.

*J. If $F$ is a non-empty closed set in $\mathbb{R}^p$ and if $x \notin F$, is there is a unique point of $F$ that is nearest to $x$?*  

Let $F = \{y \in \mathbb{R}^2: ||y-x|| = r\} \implies$ we can define a non-empty set where every element contained in the set is the same distance from $x \implies$ there is not a unique element nearest to $x$. 

#### Section 12

*A. If $A$ and $B$ are connected subsets of $\mathbb{R}^p$, give examples to show that $A \cup B, A \cap B, A \setminus B$ can be either connected for disconnected.*  

*B. If $C \subseteq \mathbb{R}^p$ is connected and $x$ is a cluster point of $C$, then $C \cup \{x\}$ is connected.*   
Assume $C^{'} = C \cup \{x\}$ is disconnected $\implies$ there exists open sets $A,B$ such that $A \cap C^{'}$ and $B \cap C^{'}$ are disjoint, non-empty, and $A \cup B = C^{'}$. Since $x \in C^{'} \implies  x \in A$ or $x \in B$, and since $x$ is a cluster point, and $A, B$ are open $\implies$ there is a neighborhood around $x$ with at least one other distinct point $implies$ if $x \in A \implies B \cap C^{'} = \emptyset$, if $x \in B \implies A \cap C^{'} = \emptyset \implies C^{'}$ must be connected, otherwise we would have a contradiction. 

*C. $C \subseteq \mathbb{R}^p$ is connected, show that its closure $C^{-}$ is also connected.*  

*E. If $K \subseteq \mathbb{R}^p$ is convex, then $K$ is connected.*  

*F. The Cantor set $F$ is wildly disconnected. Show that if $x, y \in F, x \neq y$, than there is a disconnection $A,B$ of $F$ such that $x \in B, y \in B$.*  

*H. Show that the set $A = \{(x,y) \in \mathbb{R}^2: 0 < y \leq x^2, x \neq 0 \} \cup \{(0,0)\}$ is connected in $\mathbb{R}^2$. However there does not exist a polygonal curve lying entirely in $A$ joining $(0,0)$ to other points in the set.*
