---
title: 'Math 4317 (Prof. Swiech, S''18): HW #3'
author: "Peter Williams"
date: "3/20/2018"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Section 14
*A. Let $b \in \mathbb{R}$, show $\lim \frac{b}{n} = 0$.*  

Take $\varepsilon > 0$, if $|\frac{b}{n} - 0| < \varepsilon$, there exists natural number $K(\varepsilon)$ such that $\frac{b}{n} < \frac{b}{K(\varepsilon)} < \varepsilon$. If $n \geq K(\varepsilon)$, and we choose $K(\varepsilon)$ such that $K(\varepsilon) > \frac{b}{\varepsilon} \implies \frac{b}{n} < \varepsilon \implies \lim \frac{b}{n} = 0$.  

*B. Show that $\lim (\frac{1}{n} - \frac{1}{n+1}) = 0$.*  

Take $\varepsilon > 0$, note that for $n \in \mathbb{N}, \frac{1}{n} - \frac{1}{n+1} = \frac{n + 1 -n }{n (n+1)}= \frac{1}{n(n+1)} < \frac{1}{n}$. So we choose natural number $K(\varepsilon)$ such that $\frac{1}{K(\varepsilon)} < \varepsilon$. Therefore if $n \geq K(\varepsilon) \implies \frac{1}{n} < \varepsilon$. Therefore $|\frac{1}{n} - \frac{1}{n+1} - 0| = \frac{1}{n} - \frac{1}{n+1} < \frac{1}{n} < \varepsilon \implies \lim (\frac{1}{n} - \frac{1}{n+1}) = 0$.  

*D. Let $X = (x_n)$ be a sequence in $\mathbb{R}^p$ which is convergent to $x$. Show that $\lim ||x_n|| = ||x||$. (Hint: use the Triangle Inequality.)*  

$(x_n)$ convergent with limit $x \implies$  there exists natural number $K(\varepsilon)$ such that for $n \geq K(\varepsilon),\ ||x_n - x|| < \varepsilon$. If $n \geq K(\varepsilon)$. Since by triangle inequality, $|||x_n|| - ||x||| \leq ||x_n - x||< \varepsilon \implies  \lim ||x_n|| = ||x||$.

*G. Let $d \in \mathbb{R}$ satisfy $d > 1$. Use Bernoulli's inequality to show that the sequence $(d_n)$ is not bounded in $\mathbb{R}$. Hence it is not convergent.$*   

We have the sequence $D = (d_n)$, where $d_n = d^n$. Let $d = 1 + a$ for some $a > 0 \implies d^n = (1 + a)^n > 1 + na$ by Bernoulli's inequality. For any $a > b > 0$, $(1 + a)^n > (1 + b)^n$ which implies the sequence $d_n$ is increasing. Take $M > 0$, we have $d^n > 1 + na > M > 0$, if $n > \frac{M}{a} \implies 1 + na > M$. Thus $(d_n)$ is not bounded.  

*H. Let $b \in \mathbb{R}$ satisfy $0 < b < 1$; show that $\lim (nb^n) = 0$. (Hint: use the Binomial theorem as in Example 14.8(e).)*  

Let $b = \frac{1}{1+a}, a > 0$, we have $b^n = \frac{1}{(1+a)^n}$. By Binomial theorem, $(1 + a)^n > \frac{n(n-1)}{2} a^2 \implies \frac{1}{(1 + a)^n} < \frac{2}{n(n-1)a^2}$, therefore $nb^n = \frac{n}{(1+a)^n} < \frac{2n}{n(n-1)a^2} = \frac{2}{(n-1)a^2}$. Take $\varepsilon > 0$, natural number $K(\varepsilon)$, if $n \geq K(\varepsilon)$ we have $nb^n = \frac{n}{(1+a)^n} < \frac{2}{(n-1)a^2} < \frac{2}{(K(\varepsilon)-1)a^2} < \varepsilon$. Then $|nb^n - 0| < \varepsilon \implies nb^n < \varepsilon \implies \lim nb^n = 0$.

*I. Let $X = (x_n)$ be a sequence of strictly positive real numbers such that $\lim (\frac{x_{n+1}}{x_n}) < 1$. Show that for some $r$ with $0 < r < 1$ and some $C > 0$, then we have $0 < x_n < Cr^n$ for all sufficiently large $n \in \mathbb{N}$. Use this to show that $lim (x_n) = 0$*   

Since $L = \lim (\frac{x_{n+1}}{x_n}) < 1,\ 0 < r < 1 \implies |\frac{x_{n+1}}{x_n} - L| < r$ or $0 < \frac{x_{n+1}}{x_n} < r$ for all $n \geq K(\varepsilon) \in \mathbb{N}$. Since $\frac{x_{n+1}}{x_n} < r < 1 \implies x_{n+1} < rx_n < x_n \implies x_n < \frac{x_n}{r}$. If we set $C = \frac{x_n}{r^{n+1}} > 0$, we have $x_n < Cr^n$. Since $\lim_{n \rightarrow \infty}r^n = 0 \implies lim(x_n) = 0$.

*J. Let $X = (x_n)$ be a sequence of strictly positive real numbers such that $\lim (\frac{x_{n+1}}{x_n}) > 1$. Show that $X$ is not a bounded sequence and hence is not convergent.*  

Take $\varepsilon > 0$, since $L = \lim (\frac{x_{n+1}}{x_n}) > 1 \implies |\frac{x_{n+1}}{x_n} - L|  = |L - \frac{x_{n+1}}{x_n}| < \varepsilon \implies L - \varepsilon < \frac{x_{n+1}}{x_n}$ for all $n \geq K(\varepsilon) \in \mathbb{N}$. Take $L - \varepsilon = r > 1$ when $\varepsilon$ is small. This implies $x_{n+1} > r x_n$. Take $C  = \frac{x_n}{r^{n-1}} > 0 \implies x_{n+1} > Cr^n$. Since $r > 1$, $r^n$ diverges which implies the sequence $x_{n+1}$ is not bounded or convergent. 

*K. Give and example of a convergent sequence $(x_n)$ of strictly positive real numbers such that $\lim (\frac{x_n+1}{x_n}) = 1$. Give an example of a divergent sequence with this property.*  
Consider convergent sequence $X = (x_n) = (\frac{1}{n})$. $\lim{(\frac{x_n+1}{x_n})} = 1 \implies |\frac{\frac{1}{n+1}}{\frac{1}{n}} - 1| = |\frac{-1}{n+1}| = \frac{1}{n+1} < \varepsilon,\ \varepsilon > 0$. If we choose natural number $K(\varepsilon), n \geq K(\varepsilon)$ we have $\frac{1}{n+1} < \frac{1}{K(\varepsilon)+1} < \varepsilon$, indicating $(\frac{x_n+1}{x_n})$ is a convergent sequence with limit $1$.  

Consider divergent sequence $X = (x_n) = n$. $\lim{(\frac{x_n+1}{x_n})} = 1 \implies |\frac{n+1}{n} - 1| = |\frac{1}{n}| = \frac{1}{n} < \varepsilon,\ \varepsilon > 0$. If we choose natural number $K(\varepsilon), n \geq K(\varepsilon)$ we have $\frac{1}{n} < \frac{1}{K(\varepsilon)} < \varepsilon$, indicating $(\frac{x_n+1}{x_n})$ is a convergent sequence with limit $1$.  

*L. Apply the results of Exercises 14.I and 14.J to the following sequences. (Here $0 < a < 1, 1 < b, c > 0$)*  

(a) $(a^n)$    
$\lim(\frac{x_{n+1}}{x_n}) < 1$, since $\frac{x_{n+1}}{x_n} = \frac{a^{n+1}}{a^n} = a < 1 \implies a^n$ is convergent, bounded. 

(b) $(na^n)$    
$\lim(\frac{x_{n+1}}{x_n}) < 1$, since $\frac{x_{n+1}}{x_n} = \frac{(n+1)a^{n+1}}{na^n} = (\frac{n+1}{n})a$ which tends to $1 \cdot a < 1 \implies na^n$ is convergent, bounded.

(c) $(b^n)$    
$\lim(\frac{x_{n+1}}{x_n}) > 1$, since $\frac{x_{n+1}}{x_n} = \frac{b^{n+1}}{b^n} = b > 1 \implies b^n$ is divergent, not bounded. 

(d) $(\frac{b^n}{n})$   
In this case $\lim(\frac{x_{n+1}}{x_n}) > 1$, since $\frac{x_{n+1}}{x_n} = \frac{\frac{b^{n+1}}{n+1}}{\frac{b^n}{n}} = (\frac{n}{n+1})b$ which tends to $1 \cdot b > 1 \implies \frac{b^n}{n}$ diverges, not bounded. 

(e) $(\frac{c^n}{n!})$      
$\lim(\frac{x_{n+1}}{x_n}) < 1$, since $\frac{x_{n+1}}{x_n} = \frac{\frac{c^{n+1}}{(n+1)!}}{\frac{c^n}{n!}} = \frac{c}{n+1}$ which tends to $0 < 1$ implying $(\frac{c^n}{n!})$ converges, bounded. 

(f) $(\frac{2^{3n}}{3^{2n}})$    
$\lim(\frac{x_{n+1}}{x_n}) < 1$, since $\frac{x_{n+1}}{x_n} = \frac{\frac{2^{3(n+1)}}{3^{2(n+1)}}}{\frac{2^{3n}}{3^{2n}}} = \frac{2^3}{1}\frac{1}{3^2} = \frac{8}{9} < 1$ implying $(\frac{2^{3n}}{3^{2n}})$ converges, bounded. 

#### Section 15
*C(a-e). For $x_n$ given by the following formulas, either establish the convergence of the divergence of the sequence $X = (x_n)$:*  
(a) $x_n = \frac{n}{n+1}$  
$x_n = \frac{n}{n+1} = \frac{1/n}{1/n}\frac{n}{n+1} = \frac{1}{1 + \frac{1}{n}}$. The limit of the sequence $Y = (y_n) = (1 + \frac{1}{n})$ clearly has limit $1 \implies \lim (x_n) = \lim \frac{1}{1 + \frac{1}{n}} = \frac{\lim 1}{\lim (1 + 1/n)} = 1 \implies$ this sequence converges to 1. 

(b) $x_n = \frac{(-1)^nn}{n+1}$ 
Let $X = (x_n) = (-1)^n, Y = (y_n) = \frac{n}{n+1}$. Using theorem 15.6.a, if $X$ converges to $x$, and $Y$ converges to $y$. $X \cdot Y$ converges to $x \cdot y$. In our case the series $(x_n) = (-1)^n$ diverges, and $(y_n) = \frac{n}{n+1}$ converges to $1 \implies \lim{X \cdot Y} = \lim X \cdot 1 = \lim X$ which diverges.  

(c) $x_n = \frac{2n}{3n^2 + 1}$ 
$x_n = \frac{2n}{3n^2 + 1} = \frac{1/n}{1/n}\frac{2n}{3n^2 + 1} = \frac{2}{3n  + \frac{1}{n}}$. We estimate the limit to be $0 \implies$ for $n \geq K(\varepsilon),\ |\frac{2}{3n + 1/n} - 0|  = \frac{2}{3n + 1/n} < \frac{2}{3K(\varepsilon) + 1/K(\varepsilon)} < \varepsilon,\ \varepsilon > 0 \implies (x_n) \rightarrow 0$. Converges. 

(d) $x_n = \frac{2n^2 + 3}{3n^2 + 1}$  
$x_n = \frac{2n^2 + 3}{3n^2 + 1} = \frac{1/n^2}{1/n^2}\frac{2n^2 + 3}{3n^2 + 1} = \frac{2 + 3/n^2}{3 + 1/n^2} \rightarrow \frac{2}{3}$. Converges.   

(e) $x_n = n^2 - n = n(n-1)$  
The sequence $(x_n) = n(n-1)$ is clearly divergent, since for all $M > 0,\ n \geq M$, $n(n-1) > M(M-1) > 0$. Diverges. 

*E. If $X$ and $Y$ are sequences in $\mathbb{R}^p$ and if $X \cdot Y$ converges, do $X$ and $Y$ converge and have $\lim(X \cdot Y) = \lim(X) \cdot \lim(Y)$*  

As an example, if we take sequences $X = (x_n) = (-1)^n = (-1,1,-1,...)$ and $Y = (y_n) = (-1)^{n+1} = (1,-1,1,...)$, then their product $X \cdot Y = (-1,-1,-1,...)$ converges to $-1 \implies$ that the product $X \cdot Y$ converges, but each sequence $X$ and $Y$ does not have a limit, diverges. 

As another example, in the case of the constant sequences $X = (x_N) = (1,1,...)$, and $Y = (y_n) = (2,2,...)$, $X \cdot Y$ is the constant sequence $(2,2,...)$ which converges to $2$ which equals $\lim X \cdot \lim Y$. Therefore the convergence of $X \cdot Y$ converges does not necessarily mean that each sequence converges, as there are examples of both cases.  

*F. If $X = (x_n)$ is a positive sequence which converges to $x$, then $(\sqrt{x_n})$ converges to $\sqrt{x}$. (Hint: $\sqrt{x_n} - \sqrt{x} = \frac{(x_n - x)}{(\sqrt{x_n} + \sqrt{x})}$ when $x \neq 0$).*  

In the case that $\lim (x_n) = x = 0$ we have $|x_n - x|  = |x_n - 0| = x_n < \varepsilon^2,\ \varepsilon^2 > 0,\ n \geq K(\varepsilon)$, for natural number $K(\varepsilon)$. This implies $0 \leq x_n < \varepsilon^2$ for all $n \geq K(\varepsilon) \implies 0 \leq \sqrt{(x_n)} < \varepsilon$,  $\varepsilon > 0 \implies \sqrt{x_n} - 0 < \varepsilon \implies |\sqrt{x_n} - \sqrt{x}| < \varepsilon,\ n \geq K(\varepsilon) \implies \sqrt{x}$ is limit of $sqrt{x_n}$ when $x = 0$.  

For case $x > 0$, $x > 0 \implies \sqrt{x} > 0$. Since $|\sqrt{x_n} - \sqrt{x}| = \sqrt{x_n} - \sqrt{x} = \sqrt{x_n} - \sqrt{x} \cdot \frac{\sqrt{x_n} + \sqrt{x}}{\sqrt{x_n} + \sqrt{x}} = \frac{x_n - x}{\sqrt{x_n} + \sqrt{x}}$. Since $\sqrt{x} > 0$, also implies $\sqrt{x_n} + \sqrt{x} \geq \sqrt{x} > 0 \implies \frac{x_n - x}{\sqrt{x_n} + \sqrt{x}} \leq \frac{x_n - x}{\sqrt{x}} \implies$ $|\sqrt{x_n} - \sqrt{x}| \leq \frac{1}{\sqrt{x}}(x_n - x) = \frac{1}{\sqrt{x}}|x_n - x| < \varepsilon$, $\varepsilon > 0$. So if $x_n \rightarrow x \implies \sqrt{x_n} \rightarrow \sqrt{x}$ for $x > 0$. 


*L. If $0 < a \leq b$ and if $x_n = (a^n + b^n)^{\frac{1}{n}}$, then $\lim(x_n) = b$.*  

Since $0 < a \leq b \implies b^n \leq a^n + b^n \leq b^n + b^n = 2b^n \implies (b^n)^{1/n} \leq (a^n + b^n)^{1/n} \leq (2b^n)^{1/n}$, therefore, $b \leq x_n \leq 2^{1/n}b$. Since $2^{1/n} \rightarrow 1$ as $n \rightarrow \infty \implies b \leq x_n \leq b \implies \lim(x_n) = b$.

*N.Let $A \subseteq \mathbb{R}^p$ and $x \in \mathbb{R}^p$. Then $x$ is a boundary point of $A$ if and only if there is a sequence $(a_n)$ of elements in $A$ and a sequence $(b_n)$ of elements in $\mathcal{C}(A)$ such that $\lim(a_n) = x = lim(b_n).$*  

$\rightarrow$ Let $x$ be a boundary point of $A \implies$ there is a neighborhood $V = \{y \in \mathbb{R}^p: ||y - x|| < r\},\ r > 0$, that includes points in $A$ and complement $A^c$. Since $V$ is a neighborhood of $x$, by definition of the limit, there is a natural number $K_v$ such that for all $n \geq K_v,\ a_n \in V$ and $b_n \in V \implies (a_n)$ converges to $x$ and $(b_n)$ converges to $x \implies \lim(a_n) = x = \lim(b_n)$.  

$\leftarrow$ Let $x$ be limit of sequences $(a_n),\ (b_n) \implies$ there is a neigborhood $V = \{y \in \mathbb{R}^p: ||y - x|| < r\},\ r > 0$ for natural number $K_v$, such that $n \geq K_v,\ a_n \in V,\ b_n \in V \implies V$ includes points from $(a_n) \in A$ and $(b_n) \in A^c \implies x$ is a boundary point of $A$.

#### Section 16
*A. Let $x_1 \in \mathbb{R}$ satisfy $x_1 > 1$ and let $x_{n+1} = 2 - \frac{1}{x_n}$ for $n \in \mathbb{N}$. Show that the sequence $(x_n)$ is monotone and bounded. What is its limit?*  

We have $x_1 > 1$ and $x_2 = 2 - \frac{1}{x_1}$. We then have $x_1 > 2 - \frac{1}{x_1}  = x_2 > 1$ since since $1 > \frac{1}{x_1} > 0$. This implies $x_1 > x_2 > x_3 = 2 - \frac{1}{2 - \frac{1}{x_1}} > 1$. Using induction we have $x_1 > x_2 = 2 - \frac{1}{x_1} > 1$, . We then assume $x_{n-1} > x_n > 1$. For case $n+1$ we have $x_n > x_{n+1} > 1$. Since  $x_n = 2 - \frac{1}{x_{n-1}} > x_{n+1} = 2 - \frac{1}{x_n} > 1$, and since we assume $x_{n-1} > x_n > 1$ this implies  $2 - \frac{1}{x_{n-1}} > 2 - \frac{1}{x_n} > 1,\ n \in \mathbb{N}$. This shows $(x_n)$ is a monotone decreasing sequence bounded below by $1$. Knowing that this sequence has a limit $x$ that must satisfy the relation $x = 2 - \frac{1}{x} = x \implies 2 = x + \frac{1}{x}$ which is satisfied when $x = 1 \implies$ the limit of this sequence is $1$.  

*B. Let $y_1 = 1$ and $y_{n+1} = (2 + y_n)^{1/2}$ for $n \in \mathbb{N}$. Show that $(y_n)$ is monotone and bounded. What is its limit?*  

We have $y_1 = 1,\ y_2 = \sqrt{2 + 1} = \sqrt{3} < 2 \implies y_1 < y_2 < 2$. Using induction we assume $y_{n-1} < y_n < 2$. For case $n + 1$, we have $y_n < y_{n+1} < 2 \leftrightarrow \sqrt{2 + y_{n-1}} < \sqrt{2 + y_n} < 2 \implies 2 + y_{n-1} < 2 + y_{n} < 4 \implies$ directly $y_{n-1} < y_n < 2$. This shows that $(y_n)$ is a monotone increasing sequence bounded above by $2$. If a limit of $\lim(y_n) = y$ exists it must satisfy the relation, $y = \sqrt{2 + y} \implies y^2 = 2 + y$, and we have $y^2 - y - 2 = (y - 2)(y + 1) = 0$, which has roots $2,\ -1$. Since $(y_n)$ is positive increasing, its limit must be $2$. 

*E. Show that every sequence in $\mathbb{R}$ either has a monotone increasing subsequence or a monotone decreasing subseqence.*  

Take an element of the sequence $X = (x_n)$, $x_k$, such that $x_k \geq x_n,\ n > k$. This implies for each $k_1 < k_2 < ... < k_j < ...$ we have $x_{k_1} > x_{k_2} > ... > x_{k_j}$ which is a decreasing subsequence of $X$. 

Relying the on the decreasing subsequence $x_{k_1} > x_{k_2} > ... > x_{k_j},\ D = (x_{k_j})$, if we take an index $m_1 > k_{j}$, such that $x_{m_1} \notin D$, we can construct $x_{m_1} < x_{m_2} < ... < x_{m_i}$ since there exists $m_2 > m_1$ such that $x_{m_1} < x_{m_2}$ for all $m$, which is an increasing subsequence of $X$. 

*G. Determine the convergence or divergence of the sequence $(x_n)$ where, $x_n= \frac{1}{n+1} + \frac{1}{n+2} + ... + \frac{1}{2n}$ for $n \in \mathbb{N}$.*  

We have $x_1 = \frac{1}{2},\ x_2 = \frac{1}{3} + \frac{1}{4} = \frac{7}{12} > \frac{1}{2} \implies x_1 < x_2 < 1$. Using induction we assume $x_{n-1} < x_n < 1$. For the case $n + 1$, we have $x_n < x_{n+1} < 1 \leftrightarrow \frac{1}{n+1} \frac{1}{n+2} + ... + \frac{1}{2n} < \frac{1}{n+2} + \frac{1}{n+3} + ... + \frac{1}{2n + 2} < 1$. Adding $\frac{1}{n+1} > 1$ to each element we have $x_n + \frac{1}{n+1} < x_n + \frac{1}{2n + 1} + \frac{1}{2n + 2} < 1 + \frac{1}{n+1}$. Since $\frac{1}{2n + 2} + \frac{1}{2n + 1} > \frac{1}{n+1} \forall n \in \mathbb{N}$, because $\frac{n+1}{2n + 2} + \frac{n+1}{2n + 1} > 1 \implies x_n < x_{n+1} \implies x_n + (\frac{1}{2n+2} + \frac{1}{2n + 1} - \frac{1}{n+1}) < 1 \implies x_n < x_{n+1} < 1\ \ \forall n \in \mathbb{N}$. This implies this sequence converges and is bounded above by $1$. 

*J. Show directly that the following are not Cauchy sequences.*  

(a)  $((-1)^n)$   
If we take $\varepsilon = 1 > 0$, for $m,n$ greater than natural number $M(\varepsilon)$, we have $|x_m - x_n| = 2 > \varepsilon$ for case $m$ odd, $n$ even, or case $m$ even, $n$ odd. For the cases $m$ odd and $n$ odd, or $m$ even and $n$ even we have $|x_m - x_n| = 0 < \varepsilon \implies$ there exists $m,n > M(\varepsilon)$ such that $|x_m - x_n| \geq \varepsilon > 0 \implies X = (x_n) = ((-1)^n)$ is not Cauchy.  

(b)  $(n + \frac{(-1)^n}{n})$  
If we consider just the case $m,n > M(\varepsilon) \in \mathbb{N},\ \varepsilon > 0$. For the case $m = n$ we have $|x_m - x_n| = 0$, but for the case $m,n$ even, $m > n$ we have $|x_m = x_n| = |m + \frac{-1^m}{m} - n - \frac{-1^n}{n}| = |m - n + (\frac{1}{m} - \frac{1}{n})| > 1 > 0$. This implies we can find a positive value of $\varepsilon$ such that $|x_m - x_n| \geq \varepsilon \implies X = (x_n) = (n + \frac{(-1)^n}{n})$ is not Cauchy.  

(c)  $(n^2)$  
For $m,n \in \mathbb{N}$ greater than natural number $M(\varepsilon)$, $\varepsilon > 0$, we have $|x_m - x_n|  = |m^2 - n^2|= 0$ for the case $m = n$. For the cases $m > n > 1$, or $1 < m < n$ have $|x_m - x_n|  = |m^2 - n^2| \geq 5$, since, for example, case $m = 3, n = 2$, |m^2 - n^2| = 3^2 - 2^2 = 5. This implies there exists $m,n > M(\varepsilon)$ such that $|x_m - x_n| \geq \varepsilon > 0 \implies X = (x_n) = n^2$ is not Cauchy.  

*M. Establish the convergence and limits of the following sequences:*    
(a)  $((1 + \frac{1}{n})^{n+1})$  
We have bound on $x_n = (1 + \frac{1}{n})^{n+1} \geq (1 + (n+1)\frac{1}{n}) = 1 + 1 + \frac{1}{n} > 2,\ \forall n \in \mathbb{N}$ by Bernoulli's Inequality, implying the sequence is bounded below by 2. For $X = (x_n) = ((1 + \frac{1}{n})^{n+1})$, we also have $\forall n \in \mathbb{N}$, $\frac{x_{n-1}}{x_n} = (\frac{\frac{n}{n-1}}{\frac{n+1}{n}})^n (\frac{1}{1 + \frac{1}{n}}) = (\frac{n}{n-1}\frac{n}{n+1})^n(\frac{n}{n+1}) = (\frac{n^2}{n^2 - 1})^n (\frac{n}{n+1}) > 1 \implies (x_n)$ is decreasing. So the sequence is bounded and decreasing. Applying the algebraic property of limits we then have $\lim_{n \to \infty}(1 + \frac{1}{n})^{n+1} = \lim_{n \to \infty}(1 + \frac{1}{n})^n \cdot \lim_{n \to \infty} (1 + \frac{1}{n}) = e * 1$  

(c)  $((1 + \frac{2}{n})^{n})$     
We can write $((1 + \frac{2}{n})^{n}) = ((1 + \frac{1}{\frac{n}{2}})^{n}) = ((1 + \frac{1}{\frac{n}{2}})^{\frac{n}{2}})^2$. If we consider the subsequence of even numbers, $n = 2k,\ k \in \mathbb{N}$, we have $((1 + \frac{1}{\frac{n}{2}})^{\frac{n}{2}})^2 = (1 + \frac{1}{k})^k \cdot (1 + \frac{1}{k})^k$, and using the algebraic property of limits, we have $\lim_{k \to \infty} (1 + \frac{1}{k})^k \cdot (1 + \frac{1}{k})^k = e \cdot e = e^2$, since the sequence has a limit, is convergent to $e^2$.

(d)  $((1 + \frac{1}{(n+1)})^{3n})$  
We can write $((1 + \frac{1}{(n+1)})^{3n}) = ((1 + \frac{1}{(n+1)})^{n})^3 = (1 + \frac{1}{(n+1)})^{n}) \cdot (1 + \frac{1}{(n+1)})^{n}) \cdot (1 + \frac{1}{(n+1)})^{n})$, the product of three convergent sequences, where the limit of each sequence $\lim_{n \to \infty}(1 + \frac{1}{n+1})^n = e \implies \lim_{n \to \infty}((1 + \frac{1}{(n+1)})^{3n}) = e \cdot e \cdot e = e^3$. 

*N. Let $0 < a_1 < b_1$ and define, for $n \in \mathbb{N}$, $a_{n+1} = (a_n b_n)^{1/2},\ \ b_{n+1} = \frac{1}{2}(a_n + b_n)$. By induction show that $a_n < b_n$, and show that $a_n$ and $b_n$ converge to the same limit.*  

Using induction, we are given $0<a_1<b_1$, and we assume $0<a_n<b_n$. For the case $n+1$ we have $0 < (a_nb_n)^{1/2} < \frac{1}{2}(an + bn) \leftrightarrow 0 < 2\sqrt{a_nb_n} < a_n + b_n \implies 0 < b_n + a_n - 2\sqrt{a_nb_n} = (\sqrt{b_n} - \sqrt{a_n})^2$. Since we assumed $b_n > a_n$, $0 < (\sqrt{b_n} - \sqrt{a_n})^2 \leftrightarrow 0 < \sqrt{b_n} - \sqrt{a_n} \implies 0 < \sqrt{a_n} < \sqrt{b_n} \implies 0 < a_n < b_n \implies 0 < a_{n+1} < b_{n+1}$.

We then take $a$ to the be the limit of $(a_n)$, and $b$ of $(b_n) \implies$ $a$ satisfies $a = \sqrt{ab}$, and $b$ satisfies $b = \frac{a+b}{2}$. This implies $b = \frac{\sqrt{ab}+b}{2} \implies b$ satisfies $b = \sqrt{ab} = a \implies (a_n)$ and $(b_n)$ converge to the same limit.   

#### Section 17
*A. For each $n \in \mathbb{N}$, let $f_n$ be defined for $x> 0$ by $f_n(x) = \frac{1}{nx}$. For what values of $x$ does limit $f_n(x)$ exist?*  

Since $x > 0,\ \frac{1}{nx}$ is defined for all $n \in \mathbb{N}$, and for fixed $x$ is decreasing in $n$ indicative of $\lim{(f_n(x))}$ existing for all $x$.  

*B. For each $n \in \mathbb{N}$, let $g_n$ be defined for $x \geq 0$ by the formula $g_n(x) = nx,\ 0 \leq x \leq \frac{1}{n}, g_n(x) = \frac{1}{nx}, \frac{1}{n} < x$. Show that $\lim(g_n(x)) = 0$ for all $x > 0$.*    

For case $x > \frac{1}{n},\ |g_n(x) - g(x)| = |\frac{1}{nx} - 0| = \frac{1}{nx}$. For $n \geq K(\varepsilon, x),\ nx \geq K(\varepsilon, x)x \implies \frac{1}{nx} \leq \frac{1}{K(\varepsilon,x)x} < \varepsilon,\ \varepsilon > 0 \implies g_n(x) \rightarrow 0 = g(x)$.

For case, $0 \leq x \leq \frac{1}{n}$ if we assume $\lim(g_n(x)) = g(x) = 0$. For $0 \leq x \leq \frac{1}{n},\ |g_n(x) - g(x)| = |nx - 0| = nx \implies$ for $\frac{1}{n} \geq x > 0$ we have for $n \in \mathbb{N}$ the graph of each $g_n(x))$ consisting of a line from from the point $(x,g_n(x)) = (1/n,n/n) \to (0,0)$ over the domain of $1/n \geq x > 0$, since for each $x$ there are infinitely many points between $1/n$ and $0 \implies$ we can find $n \geq K(\varepsilon,x) \in \mathbb{N}$, $nx \leq K(\varepsilon,x) x < \varepsilon,\ \varepsilon > 0$. 

*D. Show that, if we define $f_n$ on $\mathbb{R}$ by $f_n(x) = \frac{nx}{1 + n^2 x^2}$, then $(f_n)$ converges on $\mathbb{R}$.*  
We have $f_n(x) = x\frac{n}{1 + n^2 x^2}$ which can be separated into two functions $g_n(x) = x,\ h_n(x) = \frac{n}{1 + n^2 x^2}$. Clearly $g_n(x) = x \to x = g(x)$, $h_n(x) = \frac{n}{1 + n^2 x^2} = \frac{1}{\frac{1}{n} + nx^2} < \frac{1}{nx^2}$, since $x^2>0 \implies h(x) = 0$, and we have $|h_n(x) - h(x)| = \frac{1}{\frac{1}{n} + nx^2} \leq \frac{1}{\frac{1}{K} + Kx^2} < \varepsilon,\ \varepsilon > 0,\ n \geq K \in \mathbb{N}$. Using algebraic properties of limits we have, $\lim{f_n(x)} = \lim{g_n(x)} \cdot \lim{h_n(x)} = 0 \cdot x \implies \lim{f_n(x)} = 0,\ \implies$ convergence. 

*E. Let $h_n$ be defined on the interval $\mathbb{I} = [0,1]$ by the formula $h_n(x) = 1- nx,\ 0 \leq x \leq \frac{1}{n}, h_n(x) = 0,\ \frac{1}{n} < x \leq 1$.*  
Using the uniform norm property, for case $x = 0$, we have $h_n(x) = 1- nx \to_{n \to \infty} 1  = h(x) \implies \sup \{||h_n(x) - h(x)||: x = 0 \} = \sup \{||1 - nx - 1||: x = 0 \} = \sup_{x = 0} nx = 0$. For case $0 < x \leq \frac{1}{n},\ h_n(x) = 1 - nx \to 0 = h(x) \implies \sup \{||h_n(x) - h(x)||: 0 < x \leq \frac{1}{n}\}= \sup_{0 < x \leq \frac{1}{n}} \{||1 - nx||\} = 0$. For case $\frac{1}{n} < x \leq 1,\ h_n(x) = 0 = h(x) \implies \sup \{||h_n(x) - h(x)||: \frac{1}{n} < x \leq 1\} = \sup\{||0 - 0||\} = 0$ which implies  ...

*L. Show that the convergence in Exercise 17.B is not uniform on the domain $x \geq 0$, but that it is uniform on a set $x \geq c$, where $c >0$.*  

We have $$g_n(x) = \Big{\{}\begin{array}{rr}
  nx, & 0 \leq x \leq \frac{1}{n}  \\
  \frac{1}{nx}, & x > \frac{1}{n}
  \end{array}$$

But if we take $\sup_{x \in [0,\infty]} = \sup_{x \in [0,\infty]}|f_n(x) - f(x)|$, where $\lim f_n(x) = 0$, we have $\sup_{x \in [0,\infty]}|f_n(x) - f(x)| = 1 \implies f_n(x)$ is only pointwise convergent based on results from exercise 17.B.

*M. Is the convergence in Exercise 17.D uniform on $\mathbb{R}$?*  

We have $\lim_{n \to \infty}\frac{nx}{1 + n^2x^2}$, which for large $n$ is like $\lim_{n \to \infty}\frac{nx}{n^2x^2} = \frac{1}{x} \lim_{n \to \infty} \frac{1}{n} \to 0,\ x \neq 0$.. But if we take $x = \frac{1}{n}$, we have $|f_n(x) - f(x)| = |f_n(\frac{1}{n}) - f(\frac{1}{n})| = |\frac{1}{\frac{1}{n \frac{1}{n}} + n\frac{1}{n}} - 0| = \frac{1}{2} - 0 > \varepsilon,\ 0 < \varepsilon < 1/2 \implies f_n(x)$ does not converge uniformly. 

#### Section 18
*A. Determine the limit superior and the limit inferior of the following bounded sequences in $\mathbb{R}$.*  
(a)  $((-1)^n)$  
Considering two subsequences of $X = (x_n)$, we have $(x_{2n}) = (1,1,...,1,..)$, and $(x_{2n-1}) = (-1,-1,...,-1,..) \implies \lim{(x_{2n})} = 1,\ \lim{(x_{2n-1})} = -1 \implies \lim \sup (x_n) = 1, \ \lim \inf (x_n) = -1$.  
(b)  $((-1)^n/n)$  
Using the same approach, $(x_n) = ((-1)^n/n) \implies (x_{2n}) = (1/2,1/4,...,1/2n,...),$ and $\lim(x_{2n}) = 0$, $(x_{2n-1}) = (-1/1,-1/3,-1/4,...,-1/(2n-1),...), \implies \lim(x_{2n-1}) = 0 \implies \lim \sup (x_n) = \lim \lim \inf (x_n) = 0$.  
(c)  $((-1)^n + 1/n)$  
$((-1)^n + 1/n) = (x_n) \implies (x_{2n}) = (1 + 1/2, 1 + 1/4, 1 + 1/6, ..., 1 + 1/2n,..), \implies \lim (x_{2n}) = 1$. $(x_{2n-1}) = (-1 + 1/1, -1 + 1/3, -1 + 1/5, ...,-1 + 1/(2n-1),..), \implies \lim(x_{2n-1}) = -1 \implies \lim \sup (x_n) = 1, \ \lim \inf (x_n) = -11$.

*D. Give a direct proof of Theorem 18.3(c).*  
$\lim \inf(x_n) + \lim \inf (y_n) \leq \lim \inf (x_n + y_n)$. By definition $\lim \inf(x_n)$ is the supremum of set $V$ such that there are at most a finite number of $n \in \mathbb{N}$ such that $x_n < v$, and denote $\lim \inf (y_n)$ as the supremum of set $U$ of $u \in \mathbb{R}$ such that there are at most a finite number of $n \in \mathbb{N}$ such that $y_n < u$. 

Let $v < \lim \inf (x_n),\ u < \lim \inf (y_n) \implies$ there are only finite $n \in \mathbb{N}$ such that $x_n < v$ and $y_n < u \implies$ only finite $n \in \mathbb{N}$ such that $x_n + y_n < v + u \implies \lim \inf (x_n) + \lim \inf (y_n) \leq v + u \implies \lim \inf (x_n) + \lim \inf (y_n) \leq \lim \inf (x_n + y_n)$.

*F. If $X = (x_n)$ is a bounded sequence of strictly positive elements in $\mathbb{R}$, show that $\lim \sup (x_n^{1/n}) \leq \lim \sup (x_{n+1}/x_n).$*  

*I. Show that $\lim \sup X = + \infty$ if and only if there is a subsequence $X^{'}$ of $X$ such that $\lim X^{'} = + \infty$.*  

