---
title: 'Math 4317 (Prof. Swiech, S''18): HW #4'
author: "Peter Williams"
date: "3/29/2018"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Section 20  
*A. Prove that if $f$ is defined for $x \geq 0$ by $f(x) = \sqrt{x}$, then $f$ is continuous at every point of its domain.*  

For $f(x) = \sqrt{x},\ \mathcal{D}(f) = \{x \in \mathbb{R}: x \geq 0\}$, let $a \in \mathcal{D}(f)$.

When $a = 0,\ |f(x) - f(a)| = |\sqrt{x} - 0| = \sqrt{x} < \varepsilon$. If we let $\delta(\varepsilon) = \varepsilon^2,$ when $x < \varepsilon^2,\ |f(x)| < \varepsilon$.

When $a \neq 0,\ |f(x) - f(a)| = |\sqrt{x} - \sqrt{a}| = \frac{|\sqrt{x} - \sqrt{a}|}{|\sqrt{x} + \sqrt{a}|} |\sqrt{x} + \sqrt{a}| = \frac{|x - a|}{|\sqrt{x} + \sqrt{a}|} < \frac{|x - a|}{\sqrt{a}} < \varepsilon \implies$ when $|x - a| < \varepsilon \sqrt{a}$, then, $|f(x) - f(a)| < \varepsilon$, thus we can choose $\delta(\varepsilon) = \varepsilon \sqrt{a} \implies$ $f$ is continuous at every point in its domain.

*B. Show that a "polynomial function"; that is, a function $f$ with the form $f(x) = a_n x^n + a_{n-1} x^{n-1} + ... + a_1 x + a_0,\ x \in \mathbb{R}$ is continuous at every point of $\mathbb{R}$.*  

Relying on the properties of algebraic combinations of continuous of functions, we construct $f$ as a combination of continuous functions to show its continuity. Considering the last term of the polynomial function, denoted here, $f_0(x) = a_0,\ f_0(x)$ is a continuous, constant function, since, for any $a \in \mathbb{R}$ we have $|f_0(x) - f_0(a)| = |a_0  - a_0| < \varepsilon = \delta(\varepsilon),\ \varepsilon > 0$. We consider the second to last term of $f$, $a_1x$, as a constant, $a_1$ multiplied by the identity function, denoted, $f_1(x) = x$. Since $f_1(x) = x$, for any real number $a \in \mathbb{R}$, we have $|f_1(x) - f_1(a)| = |x - a| < \varepsilon = \delta(\varepsilon),\ \varepsilon > 0 \implies a_1f_1(x) = a_1x$ is continuous.

Relying on the continuity of $f_1(x) = x$ multiplied by any constant, we can construct higher order terms of $f$ through repeated multiplication of $f_1(x)$, e.g. $a_2 \cdot f_1(x) \cdot f_1(x) = a_2 x^2$ and $a_n\prod_{j=1}^{n}f_1(x) = a_n \cdot f_1(x) \cdot f_1(x) \cdot...\cdot f_1(x) = a_nx^n$, and so on, where each term constructed $a_nx^n$ is continuous on $\mathbb{R}$ since it is constructed via algebraic combinations of continuous functions $\implies f(x) = a_n x^n + a_{n-1} x^{n-1} + ... + a_1 x + a_0,$ is continuous at every point $x \in \mathbb{R}$.  

*E. Let $f$ be the function on $\mathbb{R} \to \mathbb{R}$ defined by $f(x) = x,\ x$ irrational, $f(x) = 1 - x,\ x$ rational. Show that $f$ is continuous at $x = \frac{1}{2}$ and discontinuous elsewhere.*  

Considering the point $a = \frac{1}{2}$, we have $f(a) = \frac{1}{2}$, and $|f(x) - f(a)| = |1 - x - \frac{1}{2}| = |\frac{1}{2} - x| = |x - a| < \varepsilon < \delta(\varepsilon)$. So if $|f(x) - f(a)| < \varepsilon = \delta(\varepsilon) > 0 \implies |x - a| < \delta(\varepsilon)$, and then we have $f$ continuous at the point $a = \frac{1}{2}$. 
For the case $a \neq \frac{1}{2},\ a$ irrational, take a sequence $X = (x_n)$ of rational numbers converging to $a$. Since the sequence $(f(x_n))$ converges to $1 - a$, and we have $f(a) = a$, $f$ is not continuous at irrational points by the Discontinuity Criterion. 
For the case $a \neq \frac{1}{2},\ a$ rational, take a sequence $Y = (Y_n)$ of irrational numbers converging to $a$, the sequence (f(y_n)) converges to $a$, but $f(a) = 1 - a$, which equation is only satisfied when $a = \frac{1}{2}$, thus $f$ is not continuous for rational numbers at any point other than $\frac{1}{2}$.

*F.Let $f$ be continuous on $\mathbb{R} \to \mathbb{R}$. Show that if $f(x) = 0$ for rational $x$, then $f(x) = 0$ for all $x \in \mathbb{R}$.*  

Every real point, $x \in \mathbb{R}$ is the limit of a sequence of rational numbers. If $f$ is continuous $\implies$ for a sequence of rational numbers $X = (x_n) \to x$, we have $(f(x_n)) = 0,$ for all $n \in \mathbb{N}$. Since $f$ is continuous at each rational point $x \in \mathbb{R}$, we can find $|f(x_n) - f(x)| < \varepsilon,\ \varepsilon > 0$, and $|x_n - a| < \delta(\varepsilon) \implies (f(x_n)) \to f(x) = 0, \forall x \in \mathbb{R}$.

*I. Using the results of the preceding exercise, show that the function $g$, defined on $\mathbb{R} \to \mathbb{R}$ by $g(x) = x sin(\frac{1}{x}),\ x \neq 0$, $g(x) = 0,\ x = 0$ is continuous at every point. Sketch a graph of this function.*  

*N. Let $g: \mathbb{R} \to \mathbb{R}$ satisfy the relation $g(x + y) = g(x) g(y),\ x,y \in \mathbb{R}$. Show that if $g$ is continuous at $x = 0$, then $g$ is continuous at every point. Also if $g(a) = 0$ for some $a \in \mathbb{R}$, then $g(x) = 0$ for all $x \in \mathbb{R}$.*  


#### Section 21
*I. Let $g$ be a linear function from $\mathbb{R}^p \to \mathbb{R}^q$. Show that $g$ is one-one and only if $g(x) = 0$ implies that $x = 0$.*  

*J. If $h$ is a one-one linear function from $\mathbb{R}^p \to \mathbb{R}^p$, show that the inverse function $h^{-1}$ is a linear function from $\mathbb{R}^p \to \mathbb{R}^p$.*  

*K. Show that the sum and the composition of two linear functions are linear functions.*  

*L. If $f$ is a linear map on $\mathbb{R}^p \to \mathbb{R}^q$, define $||f||_{pq} = \sup \{||f(x)||: x \in \mathbb{R}^p,\ ||x|| \leq 1 \}$. Show that the mapping $f \to ||f||_{pq}$ defines a norm on the vector space $\mathcal{L}(\mathbb{R}^p,\mathbb{R}^q)$ of all linear functions on $\mathbb{R}^p \to \mathbb{R}^q$. Show that $||f(x)|| \leq ||f||_{pq} ||x||$ for all $x \in \mathbb{R}^p$.*  


#### Section 22
*B.*  
*C.*  
*F.*  
*H.*  
*K.*  
*O.*  